/**
 * QXL DIAGNOSTICS — SINGLE SOURCE OF TRUTH TEST & PACKAGE CATALOGUE
 *
 * All prices, MRPs, parameter counts, fasting instructions, TAT, sample types,
 * and canonical URL paths across /tests, test detail pages, /book, AI Assistant,
 * and llms.txt MUST consume from this master data file.
 */

export interface MasterCatalogEntry {
  id: string;
  name: string;
  shortName: string;
  category: string;
  price: number; // Discounted Price
  mrp: number;   // Price MRP
  parametersCount: number;
  paramText: string;
  fasting: boolean;
  fastingInstruction: string;
  sampleType: string;
  tat: string;
  slug: string;
  icon: string;
  popular?: boolean;
  aliases: string[];
  homeCollectionAvailable: boolean;
  kind: 'test' | 'package';
  includes?: string;
}

export const MASTER_CATALOGUE: MasterCatalogEntry[] = [
  // ── CORE BLOOD & ROUTINE TESTS ─────────────────────────────────────────────
  {
    id: "cbc",
    name: "Complete Blood Count (CBC)",
    shortName: "CBC",
    category: "Blood Tests",
    price: 266,
    mrp: 350,
    parametersCount: 26,
    paramText: "26 Parameters",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "EDTA Whole Blood",
    tat: "6 Hours (Same Day)",
    slug: "/cbc-test",
    icon: "🩸",
    popular: true,
    aliases: ["cbc", "hemogram", "complete blood count", "cbp", "full blood count", "haemogram", "complete blood count (cbc)"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "hba1c",
    name: "Haemoglobin A1c (HbA1c)",
    shortName: "HbA1c",
    category: "Diabetes",
    price: 399,
    mrp: 720,
    parametersCount: 2,
    paramText: "2 Parameters",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "EDTA Whole Blood",
    tat: "6 Hours (Same Day)",
    slug: "/hba1c-test",
    icon: "🍬",
    popular: true,
    aliases: ["hba1c", "glycated hemoglobin", "3 month sugar test", "a1c", "haemoglobin a1c"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "fbs",
    name: "Fasting Plasma Glucose",
    shortName: "Fasting Glucose",
    category: "Diabetes",
    price: 39,
    mrp: 70,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: true,
    fastingInstruction: "8-10 Hrs Fasting Required",
    sampleType: "Fluoride Plasma",
    tat: "4 Hours",
    slug: "/fasting-plasma-glucose",
    icon: "🩸",
    popular: true,
    aliases: ["fbs", "fasting glucose", "fasting plasma glucose", "fasting blood sugar"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "ppbs",
    name: "Postprandial Blood Glucose",
    shortName: "PP Glucose",
    category: "Diabetes",
    price: 39,
    mrp: 70,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "2 Hours Post Meal",
    sampleType: "Fluoride Plasma",
    tat: "4 Hours",
    slug: "/postprandial-blood-glucose",
    icon: "🩸",
    popular: true,
    aliases: ["ppbs", "pp glucose", "postprandial blood glucose", "post prandial blood sugar"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "rbs",
    name: "Random Plasma Glucose",
    shortName: "Random Glucose",
    category: "Diabetes",
    price: 46,
    mrp: 70,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Fluoride Plasma",
    tat: "4 Hours",
    slug: "/random-plasma-glucose",
    icon: "🩸",
    popular: false,
    aliases: ["rbs", "random glucose", "random plasma glucose"],
    homeCollectionAvailable: true,
    kind: "test"
  },

  // ── THYROID PANEL ─────────────────────────────────────────────────────────
  {
    id: "thyroid-profile",
    name: "Thyroid Profile (TSH, Free T4 and Free T3)",
    shortName: "Thyroid Profile",
    category: "Thyroid",
    price: 427,
    mrp: 550,
    parametersCount: 3,
    paramText: "3 Parameters",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours (Same Day)",
    slug: "/thyroid-test",
    icon: "🦋",
    popular: true,
    aliases: ["thyroid profile", "t3 t4 tsh", "total thyroid panel", "thyroid profile (tsh, free t4 and free t3)", "tft"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "tsh",
    name: "Thyroid-Stimulating Hormone (TSH)",
    shortName: "TSH",
    category: "Thyroid",
    price: 190,
    mrp: 280,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "4–6 Hours",
    slug: "/tsh-test",
    icon: "🦋",
    popular: true,
    aliases: ["tsh", "ultrasensitive tsh", "thyroid-stimulating hormone"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "ft3",
    name: "Free Triiodothyronine (FT3)",
    shortName: "FT3",
    category: "Thyroid",
    price: 370,
    mrp: 530,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/free-triiodothyronine",
    icon: "🦋",
    popular: false,
    aliases: ["ft3", "free t3", "free triiodothyronine"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "ft4",
    name: "Free Thyroxine (FT4)",
    shortName: "FT4",
    category: "Thyroid",
    price: 370,
    mrp: 530,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/free-thyroxine",
    icon: "🦋",
    popular: false,
    aliases: ["ft4", "free t4", "free thyroxine"],
    homeCollectionAvailable: true,
    kind: "test"
  },

  // ── ORGAN FUNCTION PANELS & BIOCHEMISTRY ──────────────────────────────────
  {
    id: "lipid-profile",
    name: "Lipid Profile",
    shortName: "Lipid Profile",
    category: "Heart",
    price: 400,
    mrp: 600,
    parametersCount: 8,
    paramText: "8 Parameters",
    fasting: true,
    fastingInstruction: "10-12 Hrs Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours (Same Day)",
    slug: "/lipid-profile-test",
    icon: "❤️",
    popular: true,
    aliases: ["lipid profile", "cholesterol test", "lipid panel", "triglycerides"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "lft",
    name: "Liver Function Test Panel",
    shortName: "LFT",
    category: "Liver",
    price: 449,
    mrp: 780,
    parametersCount: 11,
    paramText: "11 Parameters",
    fasting: true,
    fastingInstruction: "8-10 Hrs Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours (Same Day)",
    slug: "/liver-function-test",
    icon: "🧪",
    popular: true,
    aliases: ["lft", "liver function test panel", "hepatic panel"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "kft",
    name: "Kidney Function Test Panel",
    shortName: "KFT / RFT",
    category: "Kidney",
    price: 449,
    mrp: 1150,
    parametersCount: 10,
    paramText: "10 Parameters",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum & Plasma",
    tat: "6 Hours (Same Day)",
    slug: "/kidney-function-test",
    icon: "💧",
    popular: true,
    aliases: ["kft", "rft", "kidney function test panel", "renal function test"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "creatinine",
    name: "Creatinine with Estimated Glomerular Filtration Rate",
    shortName: "Creatinine & eGFR",
    category: "Kidney",
    price: 96,
    mrp: 150,
    parametersCount: 2,
    paramText: "2 Parameters",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "4 Hours",
    slug: "/creatinine-test",
    icon: "🧪",
    popular: true,
    aliases: ["creatinine", "serum creatinine", "egfr", "creatinine with estimated glomerular filtration rate"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "uric-acid",
    name: "Uric Acid",
    shortName: "Uric Acid",
    category: "Kidney",
    price: 160,
    mrp: 250,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "4 Hours",
    slug: "/uric-acid-test",
    icon: "🦴",
    popular: false,
    aliases: ["uric acid", "gout test", "serum urate"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "crp",
    name: "C-Reactive Protein",
    shortName: "CRP",
    category: "Blood Tests",
    price: 380,
    mrp: 550,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/crp-test",
    icon: "⚡",
    popular: true,
    aliases: ["crp", "c-reactive protein", "c reactive protein"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "esr",
    name: "Erythrocyte Sedimentation Rate",
    shortName: "ESR",
    category: "Blood Tests",
    price: 90,
    mrp: 120,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "EDTA Blood",
    tat: "4 Hours",
    slug: "/esr-test",
    icon: "🧪",
    popular: true,
    aliases: ["esr", "erythrocyte sedimentation rate", "sed rate"],
    homeCollectionAvailable: true,
    kind: "test"
  },

  // ── VITAMINS & MINERALS ───────────────────────────────────────────────────
  {
    id: "vitamin-d",
    name: "25-Hydroxy Vitamin D",
    shortName: "Vitamin D",
    category: "Vitamins",
    price: 440,
    mrp: 1300,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours (Same Day)",
    slug: "/vitamin-d-test",
    icon: "☀️",
    popular: true,
    aliases: ["vitamin d", "25-hydroxy vitamin d", "vitamin d3"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "vitamin-b12",
    name: "Vitamin B12",
    shortName: "Vitamin B12",
    category: "Vitamins",
    price: 615,
    mrp: 1600,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours (Same Day)",
    slug: "/vitamin-b12-test",
    icon: "⚡",
    popular: true,
    aliases: ["vitamin b12", "b12 test", "cobalamin"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "ferritin",
    name: "Ferritin",
    shortName: "Ferritin",
    category: "Vitamins",
    price: 599,
    mrp: 1320,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/ferritin-test",
    icon: "🧲",
    popular: false,
    aliases: ["ferritin", "serum ferritin"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "iron-profile",
    name: "Iron Profile",
    shortName: "Iron Profile",
    category: "Vitamins",
    price: 390,
    mrp: 520,
    parametersCount: 4,
    paramText: "4 Parameters",
    fasting: true,
    fastingInstruction: "10-12 Hrs Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/iron-profile-test",
    icon: "🩸",
    popular: false,
    aliases: ["iron profile", "fe tibc"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "calcium",
    name: "Total Calcium",
    shortName: "Calcium",
    category: "Minerals",
    price: 110,
    mrp: 200,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "4 Hours",
    slug: "/total-calcium",
    icon: "🦴",
    popular: false,
    aliases: ["total calcium", "calcium test", "serum calcium"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "magnesium",
    name: "Magnesium",
    shortName: "Magnesium",
    category: "Minerals",
    price: 366,
    mrp: 450,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "4 Hours",
    slug: "/magnesium-test",
    icon: "⚡",
    popular: false,
    aliases: ["magnesium", "serum magnesium"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "electrolytes",
    name: "Electrolyte Panel",
    shortName: "Electrolytes",
    category: "Minerals",
    price: 349,
    mrp: 450,
    parametersCount: 3,
    paramText: "3 Parameters",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "4 Hours",
    slug: "/electrolyte-panel",
    icon: "💧",
    popular: true,
    aliases: ["electrolyte panel", "serum electrolytes", "sodium potassium chloride"],
    homeCollectionAvailable: true,
    kind: "test"
  },

  // ── URINE & SPECIALIZED BIOCHEMISTRY ───────────────────────────────────────
  {
    id: "urine-routine",
    name: "Urine Routine Examination",
    shortName: "Urine Routine",
    category: "Urine Tests",
    price: 120,
    mrp: 300,
    parametersCount: 18,
    paramText: "18 Parameters",
    fasting: false,
    fastingInstruction: "Provide Mid-stream Urine",
    sampleType: "Urine",
    tat: "4 Hours",
    slug: "/urine-routine",
    icon: "🧪",
    popular: true,
    aliases: ["urine routine examination", "cue", "urine routine"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "total-protein",
    name: "Total Protein",
    shortName: "Total Protein",
    category: "Liver",
    price: 106,
    mrp: 190,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "4 Hours",
    slug: "/total-protein-test",
    icon: "🧪",
    popular: false,
    aliases: ["total protein", "serum total protein"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "insulin-serum",
    name: "Insulin, Serum",
    shortName: "Fasting Insulin",
    category: "Diabetes",
    price: 660,
    mrp: 890,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: true,
    fastingInstruction: "8-10 Hrs Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/insulin-serum",
    icon: "💉",
    popular: false,
    aliases: ["insulin, serum", "fasting insulin", "serum insulin"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "c-peptide",
    name: "C-Peptide",
    shortName: "C-Peptide",
    category: "Diabetes",
    price: 900,
    mrp: 1150,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: true,
    fastingInstruction: "8-10 Hrs Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/c-peptide-test",
    icon: "🧪",
    popular: false,
    aliases: ["c-peptide", "c peptide"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "homa-ir",
    name: "HOMA-IR Calculation",
    shortName: "HOMA-IR",
    category: "Diabetes",
    price: 770,
    mrp: 1100,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: true,
    fastingInstruction: "8-10 Hrs Fasting Required",
    sampleType: "Serum & Plasma",
    tat: "6 Hours",
    slug: "/homa-ir-calculation",
    icon: "📈",
    popular: false,
    aliases: ["homa-ir calculation", "homa ir", "insulin resistance test"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "uacr",
    name: "Urine Albumin-Creatinine Ratio",
    shortName: "Urine ACR",
    category: "Kidney",
    price: 460,
    mrp: 590,
    parametersCount: 2,
    paramText: "2 Parameters",
    fasting: false,
    fastingInstruction: "First Morning Urine Preferred",
    sampleType: "Urine",
    tat: "6 Hours",
    slug: "/urine-albumin-creatinine-ratio",
    icon: "🧪",
    popular: false,
    aliases: ["urine albumin-creatinine ratio", "uacr", "microalbuminuria"],
    homeCollectionAvailable: true,
    kind: "test"
  },

  // ── CARDIAC & SPECIAL LIPID MARKERS ───────────────────────────────────────
  {
    id: "apolipoprotein-b",
    name: "Apolipoprotein B",
    shortName: "Apo B",
    category: "Heart",
    price: 566,
    mrp: 665,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: true,
    fastingInstruction: "10-12 Hrs Fasting Required",
    sampleType: "Serum",
    tat: "12 Hours",
    slug: "/apolipoprotein-b",
    icon: "❤️",
    popular: false,
    aliases: ["apolipoprotein b", "apo b"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "lipoprotein-a",
    name: "Lipoprotein(a)",
    shortName: "Lp(a)",
    category: "Heart",
    price: 400,
    mrp: 1315,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: true,
    fastingInstruction: "10-12 Hrs Fasting Required",
    sampleType: "Serum",
    tat: "12 Hours",
    slug: "/lipoprotein-a",
    icon: "❤️",
    popular: true,
    aliases: ["lipoprotein(a)", "lp(a)", "lipoprotein a"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "homocysteine",
    name: "Homocysteine",
    shortName: "Homocysteine",
    category: "Heart",
    price: 949,
    mrp: 1550,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: true,
    fastingInstruction: "10-12 Hrs Fasting Required",
    sampleType: "Serum",
    tat: "12 Hours",
    slug: "/homocysteine-test",
    icon: "❤️",
    popular: false,
    aliases: ["homocysteine", "serum homocysteine"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "hscrp",
    name: "High-Sensitivity C-Reactive Protein",
    shortName: "hs-CRP",
    category: "Heart",
    price: 566,
    mrp: 830,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/hscrp-test",
    icon: "❤️",
    popular: true,
    aliases: ["high-sensitivity c-reactive protein", "hscrp", "hs-crp"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "hs-troponin",
    name: "High-Sensitivity Cardiac Troponin",
    shortName: "hs-Troponin",
    category: "Heart",
    price: 1166,
    mrp: 1550,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "Emergency Processing Available",
    sampleType: "Serum",
    tat: "2–4 Hours",
    slug: "/high-sensitivity-cardiac-troponin",
    icon: "❤️",
    popular: true,
    aliases: ["high-sensitivity cardiac troponin", "troponin i", "hs-troponin"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "nt-probnp",
    name: "N-Terminal pro-B-Type Natriuretic Peptide",
    shortName: "NT-proBNP",
    category: "Heart",
    price: 3000,
    mrp: 3500,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/nt-probnp",
    icon: "❤️",
    popular: false,
    aliases: ["n-terminal pro-b-type natriuretic peptide", "nt-probnp", "bnp"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "ck-mb",
    name: "Creatine Kinase-MB Mass",
    shortName: "CK-MB",
    category: "Heart",
    price: 450,
    mrp: 740,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "4 Hours",
    slug: "/creatine-kinase-mb-mass",
    icon: "❤️",
    popular: false,
    aliases: ["creatine kinase-mb mass", "ck-mb", "ckmb"],
    homeCollectionAvailable: true,
    kind: "test"
  },

  // ── HORMONES & REPRODUCTIVE HEALTH ───────────────────────────────────────
  {
    id: "testosterone-total",
    name: "Total Testosterone",
    shortName: "Total Testosterone",
    category: "Hormones",
    price: 700,
    mrp: 900,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "Morning Sample Preferred (7-10 AM)",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/total-testosterone",
    icon: "⚖️",
    popular: true,
    aliases: ["total testosterone", "testosterone"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "testosterone-free",
    name: "Free Testosterone",
    shortName: "Free Testosterone",
    category: "Hormones",
    price: 1550,
    mrp: 2400,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "Morning Sample Preferred",
    sampleType: "Serum",
    tat: "12 Hours",
    slug: "/free-testosterone",
    icon: "⚖️",
    popular: false,
    aliases: ["free testosterone"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "prolactin",
    name: "Prolactin",
    shortName: "Prolactin",
    category: "Hormones",
    price: 366,
    mrp: 580,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "Rest 20 Mins Before Sample Collection",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/prolactin-test",
    icon: "⚖️",
    popular: false,
    aliases: ["prolactin", "serum prolactin"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "lh",
    name: "Luteinizing Hormone",
    shortName: "LH",
    category: "Hormones",
    price: 366,
    mrp: 600,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/luteinizing-hormone",
    icon: "⚖️",
    popular: false,
    aliases: ["luteinizing hormone", "lh"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "fsh",
    name: "Follicle-Stimulating Hormone",
    shortName: "FSH",
    category: "Hormones",
    price: 366,
    mrp: 600,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/follicle-stimulating-hormone",
    icon: "⚖️",
    popular: false,
    aliases: ["follicle-stimulating hormone", "fsh"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "estradiol",
    name: "Estradiol (E2)",
    shortName: "Estradiol",
    category: "Hormones",
    price: 460,
    mrp: 700,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/estradiol-test",
    icon: "⚖️",
    popular: false,
    aliases: ["estradiol", "e2 test", "estrogen"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "progesterone",
    name: "Progesterone",
    shortName: "Progesterone",
    category: "Hormones",
    price: 599,
    mrp: 840,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/progesterone-test",
    icon: "⚖️",
    popular: false,
    aliases: ["progesterone"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "amh",
    name: "Anti-Müllerian Hormone",
    shortName: "AMH",
    category: "Women's Health",
    price: 1666,
    mrp: 2100,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "12 Hours",
    slug: "/amh-test",
    icon: "🥚",
    popular: true,
    aliases: ["anti-müllerian hormone", "amh", "anti mullerian hormone", "ovarian reserve test"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "cortisol",
    name: "Cortisol",
    shortName: "Cortisol",
    category: "Hormones",
    price: 600,
    mrp: 1100,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "Specify Morning (8 AM) or Afternoon (4 PM)",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/cortisol-test",
    icon: "⚡",
    popular: false,
    aliases: ["cortisol", "serum cortisol"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "dhea-s",
    name: "Dehydroepiandrosterone Sulfate",
    shortName: "DHEA-S",
    category: "Hormones",
    price: 900,
    mrp: 1200,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "12 Hours",
    slug: "/dhea-s-test",
    icon: "⚖️",
    popular: false,
    aliases: ["dehydroepiandrosterone sulfate", "dhea-s", "dheas"],
    homeCollectionAvailable: true,
    kind: "test"
  },

  // ── MATERNITY & PRENATAL SCREENING ─────────────────────────────────────────
  {
    id: "beta-hcg",
    name: "Quantitative Beta Human Chorionic Gonadotropin",
    shortName: "Beta hCG",
    category: "Pregnancy",
    price: 499,
    mrp: 850,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/quantitative-beta-hcg",
    icon: "👶",
    popular: true,
    aliases: ["quantitative beta human chorionic gonadotropin", "beta hcg", "b-hcg"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "double-marker",
    name: "First-Trimester Double Marker Screen",
    shortName: "Double Marker",
    category: "Pregnancy",
    price: 1999,
    mrp: 2840,
    parametersCount: 2,
    paramText: "2 Biomarkers + Risk Software",
    fasting: false,
    fastingInstruction: "NT Scan Report Required",
    sampleType: "Serum",
    tat: "24 Hours",
    slug: "/first-trimester-double-marker-screen",
    icon: "👶",
    popular: false,
    aliases: ["first-trimester double marker screen", "double marker test"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "papp-a",
    name: "Pregnancy-Associated Plasma Protein A",
    shortName: "PAPP-A",
    category: "Pregnancy",
    price: 1000,
    mrp: 1625,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "24 Hours",
    slug: "/pregnancy-associated-plasma-protein-a",
    icon: "👶",
    popular: false,
    aliases: ["pregnancy-associated plasma protein a", "papp-a", "pappa"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "free-beta-hcg",
    name: "Free Beta Human Chorionic Gonadotropin",
    shortName: "Free Beta hCG",
    category: "Pregnancy",
    price: 1100,
    mrp: 1550,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "12 Hours",
    slug: "/free-beta-hcg",
    icon: "👶",
    popular: false,
    aliases: ["free beta human chorionic gonadotropin", "free beta hcg"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "triple-marker",
    name: "Second-Trimester Triple Marker Screen",
    shortName: "Triple Marker",
    category: "Pregnancy",
    price: 1999,
    mrp: 3100,
    parametersCount: 3,
    paramText: "3 Biomarkers + Risk Software",
    fasting: false,
    fastingInstruction: "Ultrasound Gestational Age Required",
    sampleType: "Serum",
    tat: "24 Hours",
    slug: "/second-trimester-triple-marker-screen",
    icon: "👶",
    popular: false,
    aliases: ["second-trimester triple marker screen", "triple marker test"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "quadruple-marker",
    name: "Second-Trimester Quadruple Marker Screen",
    shortName: "Quadruple Marker",
    category: "Pregnancy",
    price: 3299,
    mrp: 3900,
    parametersCount: 4,
    paramText: "4 Biomarkers + Risk Software",
    fasting: false,
    fastingInstruction: "Ultrasound Gestational Age Required",
    sampleType: "Serum",
    tat: "24 Hours",
    slug: "/second-trimester-quadruple-marker-screen",
    icon: "👶",
    popular: true,
    aliases: ["second-trimester quadruple marker screen", "quadruple marker test", "quad marker"],
    homeCollectionAvailable: true,
    kind: "test"
  },

  // ── AUTOIMMUNE & RHEUMATOLOGY ─────────────────────────────────────────────
  {
    id: "ana-screen",
    name: "Antinuclear Antibody Screen",
    shortName: "ANA Screen",
    category: "Autoimmune",
    price: 800,
    mrp: 1650,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "12 Hours",
    slug: "/antinuclear-antibody-screen",
    icon: "🛡️",
    popular: true,
    aliases: ["antinuclear antibody screen", "ana screen"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "ana-profile",
    name: "Antinuclear Antibody Profile",
    shortName: "ANA Profile",
    category: "Autoimmune",
    price: 3999,
    mrp: 5500,
    parametersCount: 12,
    paramText: "12 ENA Antibodies",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "24 Hours",
    slug: "/antinuclear-antibody-profile",
    icon: "🛡️",
    popular: true,
    aliases: ["antinuclear antibody profile", "ana profile", "ena 12 panel"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "ana-ifa",
    name: "Antinuclear Antibody by HEp-2 Indirect Immunofluorescence",
    shortName: "ANA IFA",
    category: "Autoimmune",
    price: 960,
    mrp: 1350,
    parametersCount: 1,
    paramText: "Pattern & Titer Reporting",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "24 Hours",
    slug: "/ana-hep-2-ifa",
    icon: "🔬",
    popular: true,
    aliases: ["antinuclear antibody by hep-2 indirect immunofluorescence", "ana ifa", "ana hep-2"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "anti-dsdna",
    name: "Anti-Double-Stranded DNA Antibody",
    shortName: "anti-dsDNA",
    category: "Autoimmune",
    price: 1366,
    mrp: 1600,
    parametersCount: 1,
    paramText: "Quantitative ELISA / IFA",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "12 Hours",
    slug: "/anti-double-stranded-dna-antibody",
    icon: "🧬",
    popular: false,
    aliases: ["anti-double-stranded dna antibody", "dsdna", "anti dsdna"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "ena-profile",
    name: "Extractable Nuclear Antigen Profile",
    shortName: "ENA Profile",
    category: "Autoimmune",
    price: 2850,
    mrp: 5650,
    parametersCount: 6,
    paramText: "6 ENA Markers",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "24 Hours",
    slug: "/extractable-nuclear-antigen-profile",
    icon: "🛡️",
    popular: false,
    aliases: ["extractable nuclear antigen profile", "ena profile"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "anti-ccp",
    name: "Anti-Cyclic Citrullinated Peptide Antibody",
    shortName: "Anti-CCP",
    category: "Autoimmune",
    price: 1566,
    mrp: 1950,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "12 Hours",
    slug: "/anti-cyclic-citrullinated-peptide-antibody",
    icon: "🦴",
    popular: true,
    aliases: ["anti-cyclic citrullinated peptide antibody", "anti ccp", "anti-ccp"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "ra-factor",
    name: "Rheumatoid Factor",
    shortName: "RA Factor",
    category: "Autoimmune",
    price: 399,
    mrp: 680,
    parametersCount: 1,
    paramText: "Quantitative Turbidimetry",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/rheumatoid-factor",
    icon: "🦴",
    popular: true,
    aliases: ["rheumatoid factor", "rf factor", "ra factor"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "anca-ifa",
    name: "Antineutrophil Cytoplasmic Antibodies by IFA",
    shortName: "ANCA IFA",
    category: "Autoimmune",
    price: 1250,
    mrp: 3500,
    parametersCount: 2,
    paramText: "c-ANCA & p-ANCA Pattern",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "24 Hours",
    slug: "/antineutrophil-cytoplasmic-antibodies-ifa",
    icon: "🔬",
    popular: false,
    aliases: ["antineutrophil cytoplasmic antibodies by ifa", "anca ifa", "c-anca p-anca"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "pr3-antibody",
    name: "Proteinase 3 Antibody",
    shortName: "PR3 Antibody",
    category: "Autoimmune",
    price: 2100,
    mrp: 2680,
    parametersCount: 1,
    paramText: "c-ANCA Target",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "24 Hours",
    slug: "/proteinase-3-antibody",
    icon: "🛡️",
    popular: false,
    aliases: ["proteinase 3 antibody", "pr3 antibody", "pr3 anca"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "mpo-antibody",
    name: "Myeloperoxidase Antibody",
    shortName: "MPO Antibody",
    category: "Autoimmune",
    price: 2100,
    mrp: 2680,
    parametersCount: 1,
    paramText: "p-ANCA Target",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "24 Hours",
    slug: "/myeloperoxidase-antibody",
    icon: "🛡️",
    popular: false,
    aliases: ["myeloperoxidase antibody", "mpo antibody", "mpo anca"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "c3",
    name: "Complement Component C3",
    shortName: "C3 Complement",
    category: "Autoimmune",
    price: 700,
    mrp: 880,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/complement-component-c3",
    icon: "🧬",
    popular: false,
    aliases: ["complement component c3", "c3 complement"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "c4",
    name: "Complement Component C4",
    shortName: "C4 Complement",
    category: "Autoimmune",
    price: 690,
    mrp: 895,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/complement-component-c4",
    icon: "🧬",
    popular: false,
    aliases: ["complement component c4", "c4 complement"],
    homeCollectionAvailable: true,
    kind: "test"
  },

  // ── ALLERGY TESTING ───────────────────────────────────────────────────────
  {
    id: "ige-total",
    name: "Total Immunoglobulin E",
    shortName: "Total IgE",
    category: "Allergy",
    price: 690,
    mrp: 820,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/total-immunoglobulin-e",
    icon: "🌿",
    popular: true,
    aliases: ["total immunoglobulin e", "total ige", "serum ige"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "ige-specific",
    name: "Allergen-Specific Immunoglobulin E",
    shortName: "Specific IgE",
    category: "Allergy",
    price: 660,
    mrp: 1020,
    parametersCount: 1,
    paramText: "Per Allergen Panel",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "24 Hours",
    slug: "/allergen-specific-immunoglobulin-e",
    icon: "🌿",
    popular: false,
    aliases: ["allergen-specific immunoglobulin e", "specific ige"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "allergy-profile",
    name: "Allergy Profile",
    shortName: "Comprehensive Allergy Panel",
    category: "Allergy",
    price: 8075,
    mrp: 10400,
    parametersCount: 45,
    paramText: "45 Environmental & Food Allergens",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "24–48 Hours",
    slug: "/allergy-profile",
    icon: "🌿",
    popular: true,
    aliases: ["allergy profile", "allergy panel", "comprehensive allergy screening"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "food-igg-panel",
    name: "Food-Specific IgG Panel (Not Recommended for Diagnosing Food Allergy or Intolerance)",
    shortName: "Food IgG Panel",
    category: "Allergy",
    price: 14099,
    mrp: 25000,
    parametersCount: 200,
    paramText: "200 Food Antigens",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "48 Hours",
    slug: "/food-specific-igg-panel",
    icon: "🥗",
    popular: false,
    aliases: ["food-specific igg panel", "food intolerance test", "food igg panel"],
    homeCollectionAvailable: true,
    kind: "test"
  },

  // ── ONCOLOGY BIOMARKERS ───────────────────────────────────────────────────
  {
    id: "psa-total",
    name: "Total Prostate-Specific Antigen",
    shortName: "Total PSA",
    category: "Oncology",
    price: 766,
    mrp: 900,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "Avoid Cycling / Ejaculation 48h Prior",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/total-prostate-specific-antigen",
    icon: "🎗️",
    popular: true,
    aliases: ["total prostate-specific antigen", "total psa", "psa test"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "psa-free",
    name: "Free Prostate-Specific Antigen",
    shortName: "Free PSA",
    category: "Oncology",
    price: 790,
    mrp: 950,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "Avoid Cycling 48h Prior",
    sampleType: "Serum",
    tat: "12 Hours",
    slug: "/free-prostate-specific-antigen",
    icon: "🎗️",
    popular: false,
    aliases: ["free prostate-specific antigen", "free psa"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "ca-125",
    name: "Cancer Antigen 125",
    shortName: "CA-125",
    category: "Oncology",
    price: 666,
    mrp: 1210,
    parametersCount: 1,
    paramText: "Ovarian Tumour Marker",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/cancer-antigen-125",
    icon: "🎗️",
    popular: true,
    aliases: ["cancer antigen 125", "ca-125", "ca 125"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "cea",
    name: "Carcinoembryonic Antigen",
    shortName: "CEA",
    category: "Oncology",
    price: 799,
    mrp: 1050,
    parametersCount: 1,
    paramText: "GI Tumour Marker",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/carcinoembryonic-antigen",
    icon: "🎗️",
    popular: false,
    aliases: ["carcinoembryonic antigen", "cea"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "afp",
    name: "Alpha-Fetoprotein Tumour Marker",
    shortName: "AFP",
    category: "Oncology",
    price: 760,
    mrp: 920,
    parametersCount: 1,
    paramText: "Liver & Germ Cell Marker",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/alpha-fetoprotein-tumour-marker",
    icon: "🎗️",
    popular: false,
    aliases: ["alpha-fetoprotein tumour marker", "afp", "alpha fetoprotein"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "ca-19-9",
    name: "Cancer Antigen 19-9",
    shortName: "CA 19-9",
    category: "Oncology",
    price: 1349,
    mrp: 1550,
    parametersCount: 1,
    paramText: "Pancreatic Marker",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "12 Hours",
    slug: "/cancer-antigen-19-9",
    icon: "🎗️",
    popular: false,
    aliases: ["cancer antigen 19-9", "ca 19-9", "ca 19.9"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "ca-15-3",
    name: "Cancer Antigen 15-3",
    shortName: "CA 15-3",
    category: "Oncology",
    price: 1260,
    mrp: 1590,
    parametersCount: 1,
    paramText: "Breast Tumour Marker",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "12 Hours",
    slug: "/cancer-antigen-15-3",
    icon: "🎗️",
    popular: false,
    aliases: ["cancer antigen 15-3", "ca 15-3", "ca 15.3"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "beta-hcg-tumor",
    name: "Beta-hCG Tumour Marker",
    shortName: "Beta-hCG Marker",
    category: "Oncology",
    price: 499,
    mrp: 850,
    parametersCount: 1,
    paramText: "Germ Cell Marker",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/beta-hcg-tumour-marker",
    icon: "🎗️",
    popular: false,
    aliases: ["beta-hcg tumour marker", "beta-hcg tumor marker"],
    homeCollectionAvailable: true,
    kind: "test"
  },

  // ── SPECIALIZED ELECTROPHORESIS & PROTEINS ───────────────────────────────
  {
    id: "spep",
    name: "Serum Protein Electrophoresis",
    shortName: "SPEP",
    category: "Speciality Tests",
    price: 850,
    mrp: 1100,
    parametersCount: 6,
    paramText: "M-Band & Densitometry Curve",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "12 Hours",
    slug: "/serum-protein-electrophoresis",
    icon: "🧪",
    popular: true,
    aliases: ["serum protein electrophoresis", "spep", "m band test"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "ife-serum",
    name: "Serum Immunofixation Electrophoresis",
    shortName: "IFE Serum",
    category: "Speciality Tests",
    price: 7600,
    mrp: 7980,
    parametersCount: 1,
    paramText: "Monoclonal Heavy & Light Chain Typing",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "24–48 Hours",
    slug: "/serum-immunofixation-electrophoresis",
    icon: "🔬",
    popular: false,
    aliases: ["serum immunofixation electrophoresis", "ife serum", "immunofixation"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "sflc",
    name: "Serum Free Light Chains with Kappa/Lambda Ratio",
    shortName: "Freelite SFLC",
    category: "Speciality Tests",
    price: 3666,
    mrp: 4500,
    parametersCount: 3,
    paramText: "Kappa, Lambda & Ratio",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "24 Hours",
    slug: "/serum-free-light-chains-kappa-lambda-ratio",
    icon: "🔬",
    popular: true,
    aliases: ["serum free light chains with kappa/lambda ratio", "sflc", "freelite", "kappa lambda ratio"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "upep",
    name: "Urine Protein Electrophoresis",
    shortName: "UPEP",
    category: "Speciality Tests",
    price: 690,
    mrp: 895,
    parametersCount: 1,
    paramText: "Bence Jones Protein & Banding",
    fasting: false,
    fastingInstruction: "24h Urine or First Morning Sample",
    sampleType: "Urine",
    tat: "12 Hours",
    slug: "/urine-protein-electrophoresis",
    icon: "🧪",
    popular: false,
    aliases: ["urine protein electrophoresis", "upep", "bence jones protein"],
    homeCollectionAvailable: true,
    kind: "test"
  },

  // ── INFECTIOUS DISEASES & MOLECULAR DIAGNOSTICS ────────────────────────────
  {
    id: "dengue-ns1",
    name: "Dengue NS1 Antigen",
    shortName: "Dengue NS1",
    category: "Infectious Diseases",
    price: 890,
    mrp: 1400,
    parametersCount: 1,
    paramText: "ELISA Quantitative",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "4–6 Hours",
    slug: "/dengue-ns1-antigen",
    icon: "🦟",
    popular: true,
    aliases: ["dengue ns1 antigen", "dengue ns1"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "dengue-igm-igg",
    name: "Dengue IgM and IgG Antibodies",
    shortName: "Dengue Antibodies",
    category: "Infectious Diseases",
    price: 600,
    mrp: 895,
    parametersCount: 2,
    paramText: "IgM & IgG ELISA",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/dengue-igm-and-igg-antibodies",
    icon: "🦟",
    popular: false,
    aliases: ["dengue igm and igg antibodies", "dengue antibodies"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "malaria-detection",
    name: "Malaria Parasite Detection",
    shortName: "MP Test",
    category: "Infectious Diseases",
    price: 130,
    mrp: 400,
    parametersCount: 1,
    paramText: "Smear & Antigen Rapid Test",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Whole Blood",
    tat: "2–4 Hours",
    slug: "/malaria-parasite-detection",
    icon: "🦟",
    popular: true,
    aliases: ["malaria parasite detection", "mp test", "malaria antigen"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "typhoid-test",
    name: "Typhoid Fever Diagnostic Testing",
    shortName: "Typhoid Test",
    category: "Infectious Diseases",
    price: 450,
    mrp: 750,
    parametersCount: 1,
    paramText: "Typhidot IgM / Widal",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "4 Hours",
    slug: "/typhoid-fever-diagnostic-testing",
    icon: "🌡️",
    popular: false,
    aliases: ["typhoid fever diagnostic testing", "typhidot", "widal test"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "hbsag",
    name: "Hepatitis B Surface Antigen",
    shortName: "HBsAg",
    category: "Infectious Diseases",
    price: 470,
    mrp: 1025,
    parametersCount: 1,
    paramText: "CLIA Quantitative",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/hepatitis-b-surface-antigen",
    icon: "🧪",
    popular: true,
    aliases: ["hepatitis b surface antigen", "hbsag", "hep b"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "hcv",
    name: "Hepatitis C Antibody",
    shortName: "Anti-HCV",
    category: "Infectious Diseases",
    price: 1080,
    mrp: 1750,
    parametersCount: 1,
    paramText: "CLIA Quantitative",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/hepatitis-c-antibody",
    icon: "🧪",
    popular: false,
    aliases: ["hepatitis c antibody", "hcv", "anti-hcv"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "hiv-screening",
    name: "HIV-1/2 Antigen and Antibody Screening",
    shortName: "HIV 4th Gen Duo",
    category: "Infectious Diseases",
    price: 960,
    mrp: 1450,
    parametersCount: 2,
    paramText: "p24 Antigen + Antibodies",
    fasting: false,
    fastingInstruction: "Strictly Confidential",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/hiv-1-2-antigen-and-antibody-screening",
    icon: "🛡️",
    popular: true,
    aliases: ["hiv-1/2 antigen and antibody screening", "hiv duo", "hiv 4th generation"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "h1n1-pcr",
    name: "Influenza A(H1N1) RT-PCR",
    shortName: "Swine Flu PCR",
    category: "Infectious Diseases",
    price: 3600,
    mrp: 4500,
    parametersCount: 1,
    paramText: "Real-Time Multiplex PCR",
    fasting: false,
    fastingInstruction: "Nasopharyngeal Swab",
    sampleType: "VTM Swab",
    tat: "12–24 Hours",
    slug: "/influenza-a-h1n1-rt-pcr",
    icon: "🧬",
    popular: false,
    aliases: ["influenza a(h1n1) rt-pcr", "swine flu pcr", "h1n1 pcr"],
    homeCollectionAvailable: true,
    kind: "test"
  },

  // ── NEUROLOGY & ADVANCED IMMUNOLOGY ───────────────────────────────────────
  {
    id: "aqp4-antibody",
    name: "Aquaporin-4 IgG Antibody",
    shortName: "AQP4 NMO Antibody",
    category: "Neurology",
    price: 3600,
    mrp: 4935,
    parametersCount: 1,
    paramText: "CBA / IFA Cell-Based Assay",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum / CSF",
    tat: "48 Hours",
    slug: "/aquaporin-4-igg-antibody",
    icon: "🧠",
    popular: false,
    aliases: ["aquaporin-4 igg antibody", "aqp4", "nmo antibody"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "mog-antibody",
    name: "Myelin Oligodendrocyte Glycoprotein IgG1 Antibody",
    shortName: "MOG Antibody",
    category: "Neurology",
    price: 6500,
    mrp: 7490,
    parametersCount: 1,
    paramText: "CBA Cell-Based Assay",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "48 Hours",
    slug: "/myelin-oligodendrocyte-glycoprotein-igg1-antibody",
    icon: "🧠",
    popular: false,
    aliases: ["myelin oligodendrocyte glycoprotein igg1 antibody", "mog antibody", "mogad"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "nmdar-antibody",
    name: "N-Methyl-D-Aspartate Receptor Antibody",
    shortName: "NMDA Receptor Ab",
    category: "Neurology",
    price: 5600,
    mrp: 8360,
    parametersCount: 1,
    paramText: "CBA Encephalitis Marker",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "CSF / Serum",
    tat: "48 Hours",
    slug: "/n-methyl-d-aspartate-receptor-antibody",
    icon: "🧠",
    popular: false,
    aliases: ["n-methyl-d-aspartate receptor antibody", "nmdar antibody", "anti nmda"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "paraneoplastic-panel",
    name: "Paraneoplastic Neurologic Antibody Panel",
    shortName: "Paraneoplastic Panel",
    category: "Neurology",
    price: 7600,
    mrp: 8500,
    parametersCount: 8,
    paramText: "Hu, Yo, Ri, Amphiphysin, CV2, PNMA2",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum / CSF",
    tat: "3–5 Days",
    slug: "/paraneoplastic-neurologic-antibody-panel",
    icon: "🧠",
    popular: false,
    aliases: ["paraneoplastic neurologic antibody panel", "paraneoplastic panel"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "autoimmune-encephalitis",
    name: "Autoimmune Encephalitis Antibody Panel",
    shortName: "Encephalitis Panel",
    category: "Neurology",
    price: 13860,
    mrp: 24500,
    parametersCount: 6,
    paramText: "NMDAR, LGI1, CASPR2, AMPAR1/2, GABARB1/B2",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "CSF & Serum Paired",
    tat: "3–5 Days",
    slug: "/autoimmune-encephalitis-antibody-panel",
    icon: "🧠",
    popular: true,
    aliases: ["autoimmune encephalitis antibody panel", "encephalitis panel"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "oligoclonal-bands",
    name: "Oligoclonal Bands, Paired CSF and Serum",
    shortName: "OCB CSF & Serum",
    category: "Neurology",
    price: 5400,
    mrp: 6800,
    parametersCount: 2,
    paramText: "Isoelectric Focusing (IEF)",
    fasting: false,
    fastingInstruction: "Paired Sample Required",
    sampleType: "CSF & Serum",
    tat: "48 Hours",
    slug: "/oligoclonal-bands-paired-csf-and-serum",
    icon: "🧠",
    popular: false,
    aliases: ["oligoclonal bands, paired csf and serum", "ocb test", "multiple sclerosis panel"],
    homeCollectionAvailable: false,
    kind: "test"
  },
  {
    id: "coeliac-panel",
    name: "Coeliac Disease Antibody Profile",
    shortName: "Celiac Profile",
    category: "Gastroenterology",
    price: 1600,
    mrp: 2100,
    parametersCount: 3,
    paramText: "Tissue Transglutaminase tTG IgA + Total IgA",
    fasting: false,
    fastingInstruction: "Gluten Containing Diet Preferred",
    sampleType: "Serum",
    tat: "12 Hours",
    slug: "/coeliac-disease-antibody-profile",
    icon: "🌾",
    popular: true,
    aliases: ["coeliac disease antibody profile", "celiac profile", "ttg iga"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "tpo-antibody",
    name: "Thyroid Peroxidase Antibody",
    shortName: "Anti-TPO",
    category: "Thyroid",
    price: 1299,
    mrp: 1700,
    parametersCount: 1,
    paramText: "Hashimoto's Autoimmune Marker",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/thyroid-peroxidase-antibody",
    icon: "🦋",
    popular: true,
    aliases: ["thyroid peroxidase antibody", "anti tpo", "anti-tpo"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "tg-antibody",
    name: "Thyroglobulin Antibody",
    shortName: "Anti-Tg",
    category: "Thyroid",
    price: 900,
    mrp: 1400,
    parametersCount: 1,
    paramText: "1 Parameter",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Serum",
    tat: "6 Hours",
    slug: "/thyroglobulin-antibody",
    icon: "🦋",
    popular: false,
    aliases: ["thyroglobulin antibody", "anti tg", "anti-tg"],
    homeCollectionAvailable: true,
    kind: "test"
  },
  {
    id: "flow-cytometry",
    name: "Flow Cytometry Immunophenotyping for Suspected Haematologic Malignancy",
    shortName: "Leukemia/Lymphoma Flow Cytometry",
    category: "Hematology",
    price: 6900,
    mrp: 10200,
    parametersCount: 30,
    paramText: "Multi-Color Panel (CD Markers)",
    fasting: false,
    fastingInstruction: "Fresh Sample (<24h)",
    sampleType: "EDTA Blood / Bone Marrow",
    tat: "24–48 Hours",
    slug: "/flow-cytometry-immunophenotyping",
    icon: "🔬",
    popular: false,
    aliases: ["flow cytometry immunophenotyping for suspected haematologic malignancy", "flow cytometry", "leukemia immunophenotyping"],
    homeCollectionAvailable: true,
    kind: "test"
  },

  // ── PREVENTIVE HEALTH CHECKUP PACKAGES ──────────────────────────────────────
  {
    id: "q-quick-fit",
    name: "Quick Fit Package",
    shortName: "Quick Fit Package",
    category: "Preventive Package",
    price: 1770,
    mrp: 4696,
    parametersCount: 55,
    paramText: "55 Parameters",
    fasting: true,
    fastingInstruction: "8-10 Hrs Fasting Required",
    sampleType: "Blood & Urine",
    tat: "12 Hours (Same Day)",
    slug: "/book?package=q-quick-fit",
    icon: "🏋️",
    popular: false,
    aliases: ["q-quick-fit", "pkg-fit", "pkg-1770", "pkg-1", "quick fit package", "quick fit", "fitness package"],
    homeCollectionAvailable: true,
    kind: "package",
    includes: "FBS, HbA1c, eAG, Insulin, HOMA IR, Lipid Profile, Liver Function Tests, Kidney Function Tests, TSH, Vitamin D, CBC, ESR, Urine Routine & Microscopy."
  },
  {
    id: "q-diabetes-screen",
    name: "Q-Screen Diabetes Package",
    shortName: "Q-Screen Diabetes Package",
    category: "Preventive Package",
    price: 1900,
    mrp: 4960,
    parametersCount: 62,
    paramText: "62 Parameters",
    fasting: true,
    fastingInstruction: "8-10 Hrs Fasting Required",
    sampleType: "Blood & Urine",
    tat: "12 Hours (Same Day)",
    slug: "/book?package=q-diabetes-screen",
    icon: "🩸",
    popular: true,
    aliases: ["q-diabetes-screen", "q-screen-diabetes", "pkg-diabetes", "pkg-2", "pkg-1900", "q-screen diabetes package", "diabetes package", "q screen diabetes"],
    homeCollectionAvailable: true,
    kind: "package",
    includes: "FBS, HbA1c, eAG, Urine Microalbumin, Protein/Creatinine Ratio, C-Peptide, Lipid Profile, Liver Function Test, Kidney Function Test, TSH, CBC, ESR, Urine Routine & Microscopy."
  },
  {
    id: "q-master-pro",
    name: "Q-Master Health Pro Package",
    shortName: "Q-Master Health Pro Package",
    category: "Preventive Package",
    price: 4600,
    mrp: 9600,
    parametersCount: 92,
    paramText: "92 Parameters",
    fasting: true,
    fastingInstruction: "8-10 Hrs Fasting Required",
    sampleType: "Blood & Urine",
    tat: "12 Hours (Same Day)",
    slug: "/book?package=q-master-pro",
    icon: "⭐",
    popular: true,
    aliases: ["q-master-pro", "q-master-health-pro", "pkg-master-pro", "pkg-3", "pkg-4600", "q-master health pro package", "q master health pro", "master health pro"],
    homeCollectionAvailable: true,
    kind: "package",
    includes: "FBS, HbA1c, eAG, Insulin, HOMA IR, Lipid Profile, Apo A-1, Apo-B, Apo B/A1 Ratio, Liver Function Tests, Kidney Screen, Thyroid Function Tests, Vitamin D, Vitamin B12, CBC, ESR, Urine Routine, hs-CRP."
  },
  {
    id: "q-arthritis-autoimmune",
    name: "Q-Advanced Arthritis & Autoimmune Panel",
    shortName: "Q-Advanced Arthritis & Autoimmune Panel",
    category: "Preventive Package",
    price: 6900,
    mrp: 12660,
    parametersCount: 30,
    paramText: "30 Parameters",
    fasting: true,
    fastingInstruction: "8-10 Hrs Fasting Required",
    sampleType: "Blood & Urine",
    tat: "24 Hours",
    slug: "/book?package=q-arthritis-autoimmune",
    icon: "🦴",
    popular: false,
    aliases: [
      "q-arthritis-autoimmune", "q-advanced-arthritis", "pkg-arthritis", "pkg-5", "pkg-6900", 
      "q-advanced arthritis & autoimmune panel", "q-advanced arthritis and autoimmune panel", 
      "q-arthritis panel", "arthritis package", "autoimmune panel package"
    ],
    homeCollectionAvailable: true,
    kind: "package",
    includes: "RF, Anti-CCP, ANA Autoimmune Tests, Calcium, Phosphorus, Vitamin D3, Iron Studies, Thyroid, DHEA-S, Cortisol, Lipid, LFT, KFT, CBC, ESR."
  },
  {
    id: "q-onco-screen",
    name: "Q-Oncology Biomarker Panel",
    shortName: "Q-Oncology Biomarker Panel",
    category: "Preventive Package",
    price: 7900,
    mrp: 13600,
    parametersCount: 15,
    paramText: "15 Biomarkers",
    fasting: false,
    fastingInstruction: "No Fasting Required",
    sampleType: "Blood & Stool",
    tat: "24-48 Hours",
    slug: "/book?package=q-onco-screen",
    icon: "🎗️",
    popular: false,
    aliases: [
      "q-onco-screen", "q-oncology-biomarker", "pkg-oncoscreen", "pkg-4", "pkg-7900", 
      "q-oncology biomarker panel", "q-oncoscreen package", "oncoscreen package", "cancer marker screening package"
    ],
    homeCollectionAvailable: true,
    kind: "package",
    includes: "Advanced tumour-marker testing for selected diagnostic evaluation, treatment monitoring and post-treatment surveillance under clinical guidance: AFP, CEA, Beta HCG, PSA (Male), CA-125 (Female), CA-19.9, CBC, ESR, Urine Routine, Calprotectin, FOBT, Protein Electrophoresis."
  },
  {
    id: "q-cardio-risk",
    name: "Q-Cardiovascular Risk Assessment Package",
    shortName: "Q-Cardiovascular Risk Assessment Package",
    category: "Preventive Package",
    price: 9000,
    mrp: 18900,
    parametersCount: 25,
    paramText: "25 Parameters",
    fasting: true,
    fastingInstruction: "10-12 Hrs Fasting Required",
    sampleType: "Blood & Urine",
    tat: "24 Hours",
    slug: "/book?package=q-cardio-risk",
    icon: "❤️",
    popular: false,
    aliases: [
      "q-cardio-risk", "q-cardiovascular-risk", "pkg-cardiac", "pkg-6", "pkg-9000", 
      "q-cardiovascular risk assessment package", "q-hypertension & cardiovascular risk assessment", 
      "q-hypertension and cardiovascular risk assessment package", "cardiac risk package", "cardiovascular risk assessment"
    ],
    homeCollectionAvailable: true,
    kind: "package",
    includes: "Lipid + Apo Panel, Lipoprotein(a), hs-CRP, Fibrinogen, Homocysteine, NT-proBNP, Kidney Screen, Thyroid, Cortisol, Magnesium, Insulin, CBC."
  }
];

/**
 * Helper to match any search string / query parameter to a canonical MasterCatalogEntry.
 */
export function matchMasterItem(query: string): MasterCatalogEntry | undefined {
  if (!query) return undefined;
  const q = query.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
  if (!q) return undefined;

  // Direct match by ID
  const idMatch = MASTER_CATALOGUE.find(m => m.id === q);
  if (idMatch) return idMatch;

  // Direct match by alias
  const aliasMatch = MASTER_CATALOGUE.find(m => 
    m.aliases.some(a => a.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim() === q)
  );
  if (aliasMatch) return aliasMatch;

  // Partial match by name
  const nameMatch = MASTER_CATALOGUE.find(m => {
    const mn = m.name.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
    return mn.includes(q) || q.includes(mn);
  });
  if (nameMatch) return nameMatch;

  // Keyword token matching
  if (q.includes('cbc') || q.includes('hemogram') || q.includes('blood count')) {
    return MASTER_CATALOGUE.find(m => m.id === 'cbc');
  }
  if (q.includes('thyroid') || q.includes('t3') || q.includes('t4') || q.includes('tsh')) {
    return MASTER_CATALOGUE.find(m => m.id === 'thyroid-profile');
  }
  if (q.includes('hba1c') || q.includes('glycated')) {
    return MASTER_CATALOGUE.find(m => m.id === 'hba1c');
  }
  if (q.includes('lipid') || q.includes('cholesterol')) {
    return MASTER_CATALOGUE.find(m => m.id === 'lipid-profile');
  }
  if (q.includes('vitamin d') || q.includes('vit d')) {
    return MASTER_CATALOGUE.find(m => m.id === 'vitamin-d');
  }
  if (q.includes('vitamin b12') || q.includes('vit b12')) {
    return MASTER_CATALOGUE.find(m => m.id === 'vitamin-b12');
  }
  if (q.includes('full body') || q.includes('800') || q.includes('raksha')) {
    return MASTER_CATALOGUE.find(m => m.id === 'q-quick-fit');
  }

  return undefined;
}
