/**
 * QXL Diagnostics — Complete Test Catalog
 * Each entry powers a dedicated SEO page at /tests/[slug]
 * Optimised for Google AI Overviews, ChatGPT, Gemini, and Perplexity.
 */

export interface TestData {
  slug: string;
  name: string;
  shortName?: string;
  price: number;
  originalPrice?: number;
  department: string;
  category: string;
  sampleType: string;
  fastingRequired: boolean;
  fastingHours?: number;
  turnaround: string;
  metaTitle: string;
  metaDescription: string;
  heroDescription: string;
  whatIs: string;
  whyTaken: string;
  whoShouldTake: string[];
  preparation: string[];
  procedure: string;
  normalRange: string;
  highMeans: string;
  lowMeans: string;
  relatedTests: string[];
  relatedDiseases: string[];
  faqs: { question: string; answer: string }[];
  keywords: string[];
  bodyPart?: string;
  alternateNames?: string[];
}

export const TESTS_DATA: TestData[] = [
  {
    slug: 'hba1c',
    name: 'HbA1c Test (Glycated Haemoglobin)',
    shortName: 'HbA1c',
    price: 350,
    originalPrice: 700,
    department: 'Biochemistry',
    category: 'Diabetes',
    sampleType: 'Blood (EDTA tube)',
    fastingRequired: false,
    turnaround: 'Same Day',
    metaTitle: 'HbA1c Test in Bengaluru — Price, Normal Range & Preparation | QXL Diagnostics',
    metaDescription: 'Book HbA1c (Glycated Haemoglobin) test at QXL Diagnostics, Bengaluru. No fasting required. NABL certified. ₹350. Same-day report. Free home collection.',
    heroDescription: 'The HbA1c test measures your average blood sugar over the past 2–3 months — the gold standard for diagnosing and monitoring diabetes and pre-diabetes.',
    whatIs: 'HbA1c (Haemoglobin A1c or Glycated Haemoglobin) measures the percentage of haemoglobin molecules in your blood that have glucose attached. Since red blood cells live for about 120 days, HbA1c reflects your average blood glucose over the past 2–3 months — a far more reliable indicator than a single fasting glucose reading.\n\nAt QXL Diagnostics, we use HPLC (High-Performance Liquid Chromatography) — the most accurate internationally recommended method — to measure HbA1c. Our NABL-accredited lab ensures results that meet ISO 15189:2022 quality standards.',
    whyTaken: 'The HbA1c test is used to:\n- **Diagnose Type 2 Diabetes and Pre-Diabetes**: A result ≥6.5% on two separate occasions confirms diabetes; 5.7–6.4% indicates pre-diabetes.\n- **Monitor Diabetes Control**: For people already diagnosed, it helps assess whether blood sugar management (diet, exercise, medication) is working.\n- **Adjust Treatment**: Doctors use HbA1c trends to decide whether to change diabetes medications or insulin doses.\n- **Assess Complication Risk**: Higher HbA1c correlates with greater risk of diabetic complications including neuropathy, retinopathy, and nephropathy.',
    whoShouldTake: [
      'Adults above 40 years (routine screening)',
      'People with family history of diabetes',
      'Overweight or obese individuals (BMI >25)',
      'Known diabetics for monitoring (every 3 months)',
      'Women with PCOS or history of gestational diabetes',
      'People with symptoms: increased thirst, frequent urination, fatigue, blurred vision',
      'Individuals with high fasting blood sugar results',
      'Pre-diabetics — to track progression or reversal',
    ],
    preparation: [
      'No fasting required — you can eat and drink normally before the test.',
      'Inform your doctor if you have haemoglobin disorders (sickle cell, thalassaemia) as they can affect some HbA1c methods.',
      'Wear loose, comfortable clothing for easy blood draw access.',
      'Stay well hydrated — it makes the blood draw easier.',
    ],
    procedure: 'A trained phlebotomist collects a small blood sample (2–3 mL) from a vein in your arm into an EDTA (purple-top) tube. The sample is analysed using HPLC. The test takes 10–15 minutes of lab time; results are typically available the same day.',
    normalRange: 'Below 5.7%: Normal (non-diabetic)\n5.7–6.4%: Pre-diabetes\n6.5% or above: Diabetes (on two separate tests)\nFor managed diabetics: ADA target is below 7%; individualised targets may be 7–8% for elderly or high-risk patients.',
    highMeans: 'An HbA1c above 6.5% indicates diabetes. Levels above 8% suggest poorly controlled diabetes with increased risk of complications such as diabetic kidney disease, retinopathy, nerve damage, and cardiovascular disease.',
    lowMeans: 'An abnormally low HbA1c (below 4%) can indicate haemolytic anaemia, blood loss, or certain haemoglobin disorders. In treated diabetics, it may suggest hypoglycaemia risk from over-treatment.',
    relatedTests: ['blood-glucose-fasting', 'insulin', 'homa-ir', 'kidney-function-test', 'urine-microalbumin', 'lipid-profile', 'eag'],
    relatedDiseases: ['diabetes', 'pcos', 'kidney-disease', 'heart-disease'],
    faqs: [
      { question: 'Does HbA1c require fasting?', answer: 'No. Unlike fasting blood sugar, HbA1c does not require any fasting. You can eat and drink normally before the test.' },
      { question: 'What is a normal HbA1c level?', answer: 'A normal HbA1c is below 5.7%. A level of 5.7–6.4% indicates pre-diabetes, and 6.5% or above on two separate tests indicates diabetes.' },
      { question: 'How often should a diabetic patient test HbA1c?', answer: 'For well-controlled diabetes, every 6 months. For poorly controlled or recently changed treatment plans, every 3 months.' },
      { question: 'Can HbA1c be affected by anaemia?', answer: 'Yes. Certain conditions like iron-deficiency anaemia, haemolytic anaemia, and haemoglobin variants (sickle cell, thalassaemia) can falsely alter HbA1c results. Inform your doctor if you have these conditions.' },
      { question: 'What is the HbA1c test cost in Bengaluru?', answer: 'At QXL Diagnostics, the HbA1c test costs ₹350. Home collection is free across Bengaluru.' },
    ],
    keywords: ['HbA1c test Bengaluru', 'HbA1c test price Bangalore', 'glycated haemoglobin test', 'diabetes test Bangalore', 'HbA1c normal range', 'HbA1c test cost'],
    bodyPart: 'Blood',
    alternateNames: ['Glycated Haemoglobin', 'Glycosylated Haemoglobin', 'A1C', 'Haemoglobin A1c'],
  },
  {
    slug: 'complete-blood-count',
    name: 'Complete Blood Count (CBC)',
    shortName: 'CBC',
    price: 250,
    originalPrice: 500,
    department: 'Haematology',
    category: 'General Health',
    sampleType: 'Blood (EDTA tube)',
    fastingRequired: false,
    turnaround: 'Same Day',
    metaTitle: 'CBC Test in Bengaluru — Complete Blood Count Price & Normal Range | QXL Diagnostics',
    metaDescription: 'Book CBC (Complete Blood Count) test at QXL Diagnostics Bengaluru. NABL certified lab. ₹250. Same-day results. Detects anaemia, infections, clotting disorders.',
    heroDescription: 'The Complete Blood Count (CBC) is one of the most important diagnostic tests — it measures all the key components of your blood to detect anaemia, infections, clotting disorders, and much more.',
    whatIs: 'A Complete Blood Count (CBC) is a panel of blood tests that evaluates the three major types of cells in your blood: red blood cells (RBCs), white blood cells (WBCs), and platelets. It measures their count, size, shape, and relative proportions.\n\nCBC is often called a "blood panel" and is one of the most frequently ordered tests worldwide. It provides a comprehensive snapshot of your overall health and can detect a wide range of conditions.',
    whyTaken: 'CBC is used to:\n- Detect anaemia (low RBC/haemoglobin)\n- Screen for infections (elevated WBC)\n- Diagnose blood disorders (leukaemia, lymphoma, polycythaemia)\n- Monitor bone marrow function\n- Assess clotting ability (platelet count)\n- Evaluate unexplained fatigue, weakness, bruising, or bleeding\n- Monitor response to treatment (chemotherapy, anaemia treatment)',
    whoShouldTake: [
      'Annual health check-ups for all adults',
      'People with fatigue, weakness, or shortness of breath',
      'Those with suspected infection or fever',
      'Patients on chemotherapy or immunosuppressants',
      'Pregnant women (routine monitoring)',
      'People with bruising or bleeding disorders',
      'Pre-surgical evaluation',
      'Children with growth or developmental concerns',
    ],
    preparation: [
      'No fasting required for a standalone CBC test.',
      'If part of a full health package requiring fasting, fast for 10–12 hours.',
      'Stay hydrated before the test.',
      'Inform the phlebotomist if you are on blood thinners or have a clotting disorder.',
    ],
    procedure: 'A small blood sample (2–3 mL) is collected from a vein in the arm into an EDTA tube. The sample is run through an automated haematology analyser which counts and characterises each type of blood cell. A peripheral blood smear may be examined under microscope if abnormal cells are detected. Results are ready within 2–4 hours.',
    normalRange: 'Haemoglobin: Men 13.5–17.5 g/dL; Women 12–15.5 g/dL\nRBC Count: 4.5–5.5 million/µL (men); 4.0–5.0 million/µL (women)\nWBC Count: 4,500–11,000 cells/µL\nPlatelet Count: 1,50,000–4,00,000/µL\nHaematocrit: 41–53% (men); 36–46% (women)\nMCV: 80–100 fL\nMCH: 27–33 pg\nMCHC: 32–36 g/dL',
    highMeans: 'High WBC (leukocytosis): bacterial infection, inflammation, leukaemia.\nHigh RBC (polycythaemia): dehydration, lung disease, polycythaemia vera.\nHigh platelets (thrombocytosis): infection, inflammation, iron deficiency, essential thrombocythaemia.',
    lowMeans: 'Low haemoglobin/RBC (anaemia): iron deficiency, B12/folate deficiency, chronic disease, bone marrow failure.\nLow WBC (leukopenia): viral infection, autoimmune disease, chemotherapy, bone marrow disorder.\nLow platelets (thrombocytopenia): dengue fever, ITP, liver disease, bone marrow suppression.',
    relatedTests: ['peripheral-blood-smear', 'esr', 'crp', 'ferritin', 'iron-studies', 'vitamin-b12', 'folate'],
    relatedDiseases: ['anemia', 'dengue', 'tuberculosis', 'cancer-screening'],
    faqs: [
      { question: 'What does a CBC test detect?', answer: 'A CBC detects anaemia, infections (bacterial, viral), blood cancers (leukaemia, lymphoma), platelet disorders, and many other blood conditions.' },
      { question: 'Is fasting required for a CBC test?', answer: 'No, fasting is not required for a standalone CBC. If combined with a lipid profile or blood sugar, fasting for 10–12 hours is recommended.' },
      { question: 'What is the CBC test price in Bengaluru?', answer: 'At QXL Diagnostics, a CBC test costs ₹250. Free home collection is available across Bengaluru.' },
      { question: 'How long does a CBC report take?', answer: 'CBC results are typically available within 2–4 hours at our NABL-certified lab.' },
      { question: 'Can a CBC diagnose cancer?', answer: 'A CBC can suggest blood cancers like leukaemia through abnormal cell counts or morphology. However, a bone marrow biopsy is required for definitive cancer diagnosis.' },
    ],
    keywords: ['CBC test Bengaluru', 'complete blood count test price Bangalore', 'haemoglobin test Bangalore', 'blood test Bangalore', 'WBC test Bangalore'],
    bodyPart: 'Blood',
    alternateNames: ['Full Blood Count', 'FBC', 'Blood Panel', 'Haemogram'],
  },
  {
    slug: 'vitamin-d',
    name: 'Vitamin D Test (25-Hydroxy Vitamin D)',
    shortName: 'Vitamin D',
    price: 800,
    originalPrice: 1800,
    department: 'Biochemistry',
    category: 'Vitamins & Nutrition',
    sampleType: 'Blood (serum)',
    fastingRequired: false,
    turnaround: 'Same Day',
    metaTitle: 'Vitamin D Test in Bengaluru — Price, Normal Range & Home Collection | QXL Diagnostics',
    metaDescription: 'Book Vitamin D (25-OH) test at QXL Diagnostics Bengaluru. NABL certified lab. ₹800. Free home collection. Detects deficiency linked to bone pain, fatigue & immunity.',
    heroDescription: 'The Vitamin D test measures 25-hydroxy vitamin D in your blood — the most accurate way to detect vitamin D deficiency, which affects over 70% of Indians and causes bone pain, fatigue, and weakened immunity.',
    whatIs: 'The Vitamin D test measures the level of 25-hydroxyvitamin D (25(OH)D) in your blood — the best indicator of your body\'s vitamin D status. Vitamin D is produced in your skin when exposed to sunlight and is also obtained from certain foods and supplements.\n\nDespite India\'s abundant sunshine, over 70–90% of urban Indians are vitamin D deficient due to indoor lifestyles, sunscreen use, dark skin pigmentation, and poor dietary intake. Vitamin D deficiency is linked to osteoporosis, frequent infections, depression, muscle weakness, and even increased cancer risk.',
    whyTaken: 'The Vitamin D test is used to:\n- Diagnose vitamin D deficiency or insufficiency\n- Explain unexplained bone pain, muscle weakness, or fatigue\n- Monitor vitamin D supplementation response\n- Screen high-risk groups (elderly, pregnant women, vegetarians, dark-skinned individuals)\n- Assess immunity — low vitamin D increases susceptibility to infections\n- Investigate elevated parathyroid hormone (PTH) levels',
    whoShouldTake: [
      'People with bone pain, joint pain, or frequent fractures',
      'Those with unexplained fatigue or muscle weakness',
      'Elderly individuals (>60 years) — high risk of deficiency and falls',
      'Pregnant and breastfeeding women',
      'Vegetarians and vegans (limited dietary sources)',
      'People who avoid sunlight or always use sunscreen',
      'Those with osteoporosis or osteopenia',
      'People with inflammatory bowel disease or malabsorption',
      'Annual health check-ups (especially in Bengaluru\'s urban population)',
    ],
    preparation: [
      'No fasting required for the Vitamin D test.',
      'Inform your doctor about any vitamin D supplements you are taking — this can affect interpretation.',
      'No special preparation is needed.',
    ],
    procedure: 'A blood sample (2–3 mL) is collected from a vein in the arm. At QXL Diagnostics, we measure 25-hydroxy vitamin D using Chemiluminescent Immunoassay (CLIA) — the most accurate and reproducible method available in India.',
    normalRange: 'Severe deficiency: Below 10 ng/mL\nDeficiency: 10–20 ng/mL\nInsufficiency: 20–30 ng/mL\nSufficiency (Normal): 30–100 ng/mL\nToxicity risk: Above 150 ng/mL',
    highMeans: 'Vitamin D toxicity (above 150 ng/mL) is rare and usually caused by excessive supplementation. It can cause hypercalcaemia, nausea, weakness, kidney stones, and heart rhythm problems.',
    lowMeans: 'Low vitamin D causes rickets in children and osteomalacia in adults. It is associated with osteoporosis, muscle weakness, depression, frequent infections, autoimmune diseases, and increased cancer risk.',
    relatedTests: ['calcium', 'phosphorus', 'pth', 'bone-profile', 'vitamin-b12'],
    relatedDiseases: ['vitamin-deficiency', 'arthritis'],
    faqs: [
      { question: 'What is the normal range of Vitamin D?', answer: 'A normal (sufficient) vitamin D level is 30–100 ng/mL. Levels below 20 ng/mL indicate deficiency requiring treatment.' },
      { question: 'What are the symptoms of Vitamin D deficiency?', answer: 'Common symptoms include bone pain, muscle weakness, fatigue, depression, frequent colds and infections, hair loss, and impaired wound healing.' },
      { question: 'What is the Vitamin D test cost in Bengaluru?', answer: 'At QXL Diagnostics, the Vitamin D test costs ₹800. Free home collection is available across Bengaluru.' },
      { question: 'Does sunlight exposure affect Vitamin D test results?', answer: 'Sunlight exposure over days to weeks can modestly increase Vitamin D levels, but will not significantly alter your test result taken on a specific day.' },
      { question: 'How long does Vitamin D supplementation take to correct deficiency?', answer: 'With high-dose supplementation (60,000 IU weekly for 8–12 weeks), most people reach sufficient levels within 3 months. Repeat testing is recommended after supplementation.' },
    ],
    keywords: ['Vitamin D test Bengaluru', 'Vitamin D test price Bangalore', '25-OH Vitamin D test', 'Vitamin D deficiency test', 'home collection Vitamin D test Bengaluru'],
    bodyPart: 'Blood',
    alternateNames: ['25-Hydroxy Vitamin D', '25(OH)D', 'Calcidiol', 'Vitamin D3'],
  },
  {
    slug: 'thyroid-profile',
    name: 'Thyroid Profile Test (T3, T4, TSH)',
    shortName: 'Thyroid Profile',
    price: 450,
    originalPrice: 900,
    department: 'Biochemistry',
    category: 'Hormones',
    sampleType: 'Blood (serum)',
    fastingRequired: false,
    turnaround: 'Same Day',
    metaTitle: 'Thyroid Profile Test (T3 T4 TSH) in Bengaluru — Price & Normal Range | QXL Diagnostics',
    metaDescription: 'Book Thyroid Profile Test (T3, T4, TSH) at QXL Diagnostics Bengaluru. NABL certified. ₹450. Same-day report. Detects hypothyroidism, hyperthyroidism & thyroid nodules.',
    heroDescription: 'The Thyroid Profile test measures T3, T4, and TSH hormones to diagnose hypothyroidism, hyperthyroidism, and thyroid nodule activity — affecting 42 million Indians, especially women.',
    whatIs: 'The Thyroid Profile test (also called TFT — Thyroid Function Tests) measures three key hormones:\n- **TSH (Thyroid Stimulating Hormone)**: Produced by the pituitary gland; the most sensitive indicator of thyroid function\n- **T3 (Triiodothyronine)**: The active thyroid hormone that regulates metabolism\n- **T4 (Thyroxine)**: The main hormone produced by the thyroid gland\n\nThyroid disorders affect approximately 42 million Indians, making them one of the most common endocrine conditions. Women are 5–8 times more likely to develop thyroid disorders than men.',
    whyTaken: 'The Thyroid Profile test is used to diagnose:\n- Hypothyroidism (underactive thyroid) — fatigue, weight gain, hair loss, cold intolerance\n- Hyperthyroidism (overactive thyroid) — weight loss, palpitations, anxiety, tremors\n- Hashimoto\'s thyroiditis (autoimmune hypothyroidism)\n- Graves\' disease (autoimmune hyperthyroidism)\n- Thyroid nodules and goitre\n- Thyroid cancer monitoring\n- Neonatal hypothyroidism screening',
    whoShouldTake: [
      'Women over 35 (annual screening recommended)',
      'People with unexplained weight gain or weight loss',
      'Those with fatigue, depression, or brain fog',
      'People with hair loss or dry skin',
      'Women with irregular periods or fertility issues',
      'Pregnant women (thyroid disorders are common in pregnancy)',
      'People with family history of thyroid disease',
      'Patients on thyroid medication (for monitoring)',
      'Those with neck swelling or difficulty swallowing',
    ],
    preparation: [
      'No fasting required for thyroid tests.',
      'Ideally take the test in the morning — TSH levels vary throughout the day and are highest in the morning.',
      'If taking thyroid medication (levothyroxine), take the blood test before your morning dose for most accurate results.',
      'Avoid biotin supplements for 48 hours before the test as high-dose biotin can interfere with results.',
    ],
    procedure: 'A blood sample is collected from a vein in the arm. QXL Diagnostics measures T3, T4, and TSH using Chemiluminescent Immunoassay (CLIA) with high sensitivity — detecting very small changes in hormone levels that indicate early thyroid dysfunction.',
    normalRange: 'TSH: 0.4–4.0 mIU/L (varies by lab and pregnancy)\nFree T4 (fT4): 0.8–1.8 ng/dL\nFree T3 (fT3): 2.3–4.2 pg/mL\nTotal T3: 60–180 ng/dL\nTotal T4: 4.5–11.5 µg/dL',
    highMeans: 'High TSH with low T3/T4 = Hypothyroidism (underactive thyroid). High TSH with normal T3/T4 = Sub-clinical hypothyroidism. Low TSH with high T3/T4 = Hyperthyroidism (overactive thyroid).',
    lowMeans: 'Low TSH with low T3/T4 = Secondary hypothyroidism (pituitary gland problem). Low TSH alone = Possible hyperthyroidism or excessive thyroid medication.',
    relatedTests: ['anti-tpo', 'anti-tg', 'tsh', 'thyroglobulin', 'calcium'],
    relatedDiseases: ['thyroid-disorder', 'pcos', 'infertility'],
    faqs: [
      { question: 'What is the difference between TSH, T3, and T4 tests?', answer: 'TSH is the most sensitive screening test — it rises when the thyroid is underactive and falls when overactive. T3 and T4 are the actual thyroid hormones. TSH alone is sufficient for routine screening; T3 and T4 are added for diagnosis and monitoring.' },
      { question: 'What is the normal TSH level?', answer: 'Normal TSH is 0.4–4.0 mIU/L. TSH above 4.0 suggests hypothyroidism; below 0.4 suggests hyperthyroidism. Pregnancy has different ranges.' },
      { question: 'What is the Thyroid Profile test cost in Bengaluru?', answer: 'At QXL Diagnostics, the Thyroid Profile (T3, T4, TSH) costs ₹450. Free home collection is available across Bengaluru.' },
      { question: 'Can I take thyroid medication before the test?', answer: 'For most accurate results, take your blood test before your morning levothyroxine dose. Discuss timing with your doctor.' },
      { question: 'How often should I test my thyroid?', answer: 'For thyroid disease monitoring: every 3–6 months when starting treatment, then annually once stable. Annual screening for high-risk individuals (women over 40, family history).' },
    ],
    keywords: ['thyroid test Bengaluru', 'TSH test price Bangalore', 'T3 T4 TSH test Bengaluru', 'hypothyroidism test Bangalore', 'thyroid function test cost'],
    bodyPart: 'Thyroid Gland / Blood',
    alternateNames: ['TFT', 'Thyroid Function Tests', 'TSH T3 T4'],
  },
  {
    slug: 'lipid-profile',
    name: 'Lipid Profile Test (Cholesterol Panel)',
    shortName: 'Lipid Profile',
    price: 400,
    originalPrice: 800,
    department: 'Biochemistry',
    category: 'Cardiology',
    sampleType: 'Blood (serum)',
    fastingRequired: true,
    fastingHours: 10,
    turnaround: 'Same Day',
    metaTitle: 'Lipid Profile Test in Bengaluru — Cholesterol Test Price & Normal Range | QXL Diagnostics',
    metaDescription: 'Book Lipid Profile test at QXL Diagnostics Bengaluru. NABL certified. ₹400. 10-hour fasting required. Measures total cholesterol, LDL, HDL, triglycerides for heart disease risk.',
    heroDescription: 'The Lipid Profile test measures your total cholesterol, LDL (bad cholesterol), HDL (good cholesterol), and triglycerides — essential for assessing your risk of heart attack and stroke.',
    whatIs: 'A Lipid Profile (also called a Lipid Panel or Cholesterol Panel) is a blood test that measures the fat molecules (lipids) in your bloodstream:\n- **Total Cholesterol**: Overall measure of all cholesterol types\n- **LDL (Low-Density Lipoprotein)**: "Bad" cholesterol — deposits in artery walls\n- **HDL (High-Density Lipoprotein)**: "Good" cholesterol — removes cholesterol from arteries\n- **Triglycerides**: Blood fats linked to heart disease, especially with high carbohydrate/sugar intake\n- **VLDL**: Calculated measure of very low-density lipoprotein\n- **Non-HDL Cholesterol**: A composite measure increasingly used to assess cardiovascular risk',
    whyTaken: 'The Lipid Profile is essential for:\n- Assessing risk of heart attack, stroke, and coronary artery disease\n- Diagnosing hypercholesterolaemia (high cholesterol)\n- Monitoring response to cholesterol-lowering medication (statins)\n- Screening for familial hypercholesterolaemia (genetic condition)\n- Evaluating metabolic syndrome (combination of high triglycerides, low HDL, high blood pressure, and high blood sugar)',
    whoShouldTake: [
      'All adults over 20 years (every 5 years as screening)',
      'People with family history of heart disease or high cholesterol',
      'Diabetics (higher cardiovascular risk)',
      'Overweight or obese individuals',
      'Smokers and former smokers',
      'People with hypertension',
      'Those on cholesterol-lowering medications (monitoring)',
      'Individuals with unexplained pancreatitis (can be caused by very high triglycerides)',
    ],
    preparation: [
      'Fast for 10–12 hours before the test (water is allowed).',
      'Avoid alcohol for at least 24 hours before the test — alcohol raises triglycerides.',
      'Maintain your usual diet for at least 2 weeks before testing.',
      'Inform your doctor about all medications, including statins, as they affect results.',
      'Early morning fasting is ideal — book home collection at 7–8 AM.',
    ],
    procedure: 'After 10–12 hours of fasting, a blood sample (4–5 mL) is collected into a plain or serum-separator tube. The lipids are measured using enzymatic colorimetric methods. HDL is measured directly; LDL is either calculated using the Friedewald equation or measured directly for more accuracy.',
    normalRange: 'Total Cholesterol: Desirable <200 mg/dL; Borderline 200–239 mg/dL; High ≥240 mg/dL\nLDL Cholesterol: Optimal <100 mg/dL; Near Optimal 100–129 mg/dL; Borderline 130–159 mg/dL; High ≥160 mg/dL\nHDL Cholesterol: Low (risk) <40 mg/dL (men), <50 mg/dL (women); Desirable ≥60 mg/dL\nTriglycerides: Normal <150 mg/dL; Borderline 150–199 mg/dL; High 200–499 mg/dL; Very High ≥500 mg/dL',
    highMeans: 'High LDL increases risk of atherosclerosis (artery hardening), heart attack, and stroke. High triglycerides increase risk of pancreatitis and cardiovascular disease, especially combined with low HDL.',
    lowMeans: 'Low HDL is a risk factor for cardiovascular disease. Very low total cholesterol (below 150 mg/dL) can occasionally indicate malnutrition, hyperthyroidism, or liver disease.',
    relatedTests: ['hba1c', 'blood-glucose-fasting', 'crp', 'hs-crp', 'apolipoprotein-a1', 'apolipoprotein-b', 'lp-a'],
    relatedDiseases: ['heart-disease', 'diabetes', 'fatty-liver', 'hypertension'],
    faqs: [
      { question: 'How many hours of fasting is required for lipid profile?', answer: '10–12 hours of fasting is recommended for accurate triglyceride measurement. Water is allowed during fasting.' },
      { question: 'What is the normal cholesterol level?', answer: 'Total cholesterol below 200 mg/dL is desirable. LDL should ideally be below 100 mg/dL. HDL above 60 mg/dL is protective. Triglycerides should be below 150 mg/dL.' },
      { question: 'What is the lipid profile test cost in Bengaluru?', answer: 'At QXL Diagnostics, the Lipid Profile test costs ₹400 with free home collection across Bengaluru.' },
      { question: 'Can high cholesterol cause symptoms?', answer: 'High cholesterol is largely symptom-free until it causes a serious event like a heart attack or stroke. Regular testing is the only way to detect it early.' },
      { question: 'Do I need to stop statins before a lipid profile?', answer: 'No. Continue taking statins as prescribed. The test monitors whether the medication is achieving target levels, so results on medication are most useful for your doctor.' },
    ],
    keywords: ['lipid profile test Bengaluru', 'cholesterol test Bangalore', 'LDL HDL test price Bangalore', 'triglycerides test Bengaluru', 'heart disease blood test Bangalore'],
    bodyPart: 'Blood / Cardiovascular',
    alternateNames: ['Cholesterol Panel', 'Lipid Panel', 'Fasting Lipids'],
  },
  {
    slug: 'liver-function-test',
    name: 'Liver Function Test (LFT)',
    shortName: 'LFT',
    price: 500,
    originalPrice: 1000,
    department: 'Biochemistry',
    category: 'Liver',
    sampleType: 'Blood (serum)',
    fastingRequired: false,
    turnaround: 'Same Day',
    metaTitle: 'Liver Function Test (LFT) in Bengaluru — Price, Parameters & Normal Range | QXL Diagnostics',
    metaDescription: 'Book Liver Function Test (LFT) at QXL Diagnostics Bengaluru. NABL certified. ₹500. Measures SGOT, SGPT, bilirubin, albumin. Detects fatty liver, hepatitis & liver damage.',
    heroDescription: 'The Liver Function Test (LFT) measures enzymes and proteins that reveal how well your liver is working — detecting fatty liver, hepatitis, cirrhosis, and drug-induced liver damage.',
    whatIs: 'The Liver Function Test (LFT), also called Liver Profile or Hepatic Function Panel, is a group of blood tests that assess the health and function of your liver. It measures:\n- **ALT/SGPT** (Alanine Aminotransferase): Most specific for liver cell damage\n- **AST/SGOT** (Aspartate Aminotransferase): Liver and muscle enzyme\n- **ALP** (Alkaline Phosphatase): Bile duct and bone enzyme\n- **GGT** (Gamma-Glutamyl Transferase): Sensitive to alcohol and bile duct disease\n- **Bilirubin** (Total and Direct): Waste product; elevated in jaundice\n- **Total Protein and Albumin**: Proteins synthesised by the liver\n- **Globulin and A/G Ratio**: Immune proteins',
    whyTaken: 'LFT is used to:\n- Diagnose fatty liver disease (NAFLD — extremely common in urban India)\n- Detect hepatitis A, B, C infections\n- Monitor liver damage from alcohol\n- Assess drug-induced liver injury (paracetamol, statins, anti-TB drugs)\n- Investigate jaundice (yellowing of skin/eyes)\n- Monitor known liver diseases (cirrhosis, autoimmune hepatitis)\n- Screen before starting medications that can affect the liver',
    whoShouldTake: [
      'People with unexplained fatigue, nausea, or right-upper abdominal pain',
      'Those with suspected jaundice (yellow skin or eyes)',
      'Heavy alcohol consumers',
      'People on long-term medications (paracetamol, statins, anti-TB drugs)',
      'Patients with diabetes, obesity, or metabolic syndrome (high risk of fatty liver)',
      'Those with hepatitis B or C (for monitoring)',
      'Annual health check-ups',
      'Pre-surgical evaluation',
    ],
    preparation: [
      'No fasting is strictly required, but fasting for 4–8 hours improves accuracy of some parameters.',
      'Avoid heavy exercise for 24 hours before the test — it elevates AST and ALT.',
      'Avoid alcohol for 48 hours before testing.',
      'Inform your doctor about all medications including supplements.',
    ],
    procedure: 'A blood sample (5 mL) is drawn from a vein in the arm and analysed using automated biochemistry analyser. The entire panel of liver enzymes, proteins, and bilirubin is measured simultaneously.',
    normalRange: 'ALT/SGPT: 7–40 U/L\nAST/SGOT: 10–40 U/L\nALP: 44–147 U/L\nGGT: 8–61 U/L (men), 5–36 U/L (women)\nTotal Bilirubin: 0.1–1.2 mg/dL\nDirect Bilirubin: 0–0.3 mg/dL\nTotal Protein: 6.3–8.2 g/dL\nAlbumin: 3.4–5.0 g/dL',
    highMeans: 'Elevated ALT/SGPT: Hepatitis, fatty liver, alcohol damage, drug toxicity.\nHigh ALP: Bile duct obstruction, bone disease, liver disease.\nHigh Bilirubin: Jaundice, haemolysis, bile duct obstruction, liver disease.',
    lowMeans: 'Low Albumin: Severe liver disease (cirrhosis), malnutrition, or protein-losing nephropathy.\nLow Total Protein: Malnutrition, liver failure, kidney disease.',
    relatedTests: ['ultrasound-abdomen', 'hepatitis-b-surface-antigen', 'hepatitis-c-antibody', 'hbs-quantitative', 'ggt', 'fibroscan'],
    relatedDiseases: ['fatty-liver', 'hepatitis', 'fever-evaluation'],
    faqs: [
      { question: 'What does an LFT test detect?', answer: 'LFT detects liver conditions including fatty liver disease (NAFLD), viral hepatitis (A, B, C), alcohol-induced liver damage, drug toxicity, cirrhosis, bile duct obstruction, and jaundice.' },
      { question: 'What are normal LFT values?', answer: 'Normal ALT/SGPT is 7–40 U/L; AST/SGOT is 10–40 U/L. Total bilirubin should be below 1.2 mg/dL, and albumin should be 3.4–5.0 g/dL.' },
      { question: 'What is the LFT test cost in Bengaluru?', answer: 'At QXL Diagnostics, the Liver Function Test costs ₹500. Free home collection is available across Bengaluru.' },
      { question: 'Can high SGPT/ALT indicate fatty liver?', answer: 'Yes. Mildly elevated ALT (1.5–3× normal) is a common finding in Non-Alcoholic Fatty Liver Disease (NAFLD), which is very prevalent in urban India among people with diabetes, obesity, and metabolic syndrome.' },
      { question: 'What causes jaundice?', answer: 'Jaundice (elevated bilirubin) can be caused by liver disease (hepatitis, cirrhosis), bile duct blockage (gallstones, cancer), or increased red blood cell breakdown (haemolysis).' },
    ],
    keywords: ['liver function test Bengaluru', 'LFT test price Bangalore', 'SGPT SGOT test Bengaluru', 'fatty liver test Bangalore', 'hepatitis test Bengaluru'],
    bodyPart: 'Liver',
    alternateNames: ['Liver Profile', 'Hepatic Function Panel', 'LFT', 'SGOT SGPT test'],
  },
  {
    slug: 'kidney-function-test',
    name: 'Kidney Function Test (KFT / RFT)',
    shortName: 'KFT',
    price: 450,
    originalPrice: 900,
    department: 'Biochemistry',
    category: 'Kidney',
    sampleType: 'Blood (serum)',
    fastingRequired: false,
    turnaround: 'Same Day',
    metaTitle: 'Kidney Function Test (KFT) in Bengaluru — Price, Parameters & Normal Range | QXL Diagnostics',
    metaDescription: 'Book Kidney Function Test (KFT) at QXL Diagnostics Bengaluru. NABL certified. ₹450. Measures creatinine, urea, uric acid, electrolytes. Detects CKD, kidney stones & renal failure.',
    heroDescription: 'The Kidney Function Test (KFT) detects chronic kidney disease (CKD), kidney stones, and renal damage before symptoms appear — critical since CKD is largely silent in early stages.',
    whatIs: 'The Kidney Function Test (KFT), also called Renal Function Tests (RFT) or Renal Profile, is a group of blood tests that assess how well your kidneys are filtering waste from your blood. It includes:\n- **Serum Creatinine**: Most important marker of kidney function\n- **eGFR** (Estimated GFR): Calculates kidney filtration rate\n- **Blood Urea Nitrogen (BUN)**: Waste product filtered by kidneys\n- **Serum Uric Acid**: Linked to gout and kidney stones\n- **Electrolytes**: Sodium, Potassium, Chloride, Bicarbonate\n- **Calcium and Phosphorus**: Regulated by the kidneys',
    whyTaken: 'KFT is essential for:\n- Screening for Chronic Kidney Disease (CKD) — silent until advanced stages\n- Monitoring kidney function in diabetics and hypertensives (leading causes of CKD)\n- Assessing kidney damage from medications (NSAIDs, contrast dyes, antibiotics)\n- Evaluating gout (high uric acid)\n- Monitoring kidney stones and urinary tract health\n- Pre-surgical assessment',
    whoShouldTake: [
      'Diabetics — kidney damage (diabetic nephropathy) is a major complication',
      'Hypertensive patients — high blood pressure damages kidneys over time',
      'People over 50 years (annual screening)',
      'Those with family history of kidney disease',
      'Patients on NSAIDs (ibuprofen, diclofenac) or other potentially nephrotoxic drugs',
      'People with recurrent UTIs or kidney stones',
      'Overweight individuals with metabolic syndrome',
      'Those with swelling in feet, ankles, or around eyes',
    ],
    preparation: [
      'No strict fasting required, but avoid heavy protein meals for 24 hours (can affect creatinine and urea).',
      'Stay well hydrated — drink plenty of water before the test.',
      'Inform your doctor about all medications, especially NSAIDs and diuretics.',
      'Avoid strenuous exercise 24 hours before testing (can raise creatinine temporarily).',
    ],
    procedure: 'A blood sample (5 mL) is collected and analysed for multiple kidney markers simultaneously using automated biochemistry analyser. eGFR is calculated from creatinine using the CKD-EPI or MDRD formula.',
    normalRange: 'Creatinine: Men 0.7–1.2 mg/dL; Women 0.5–1.0 mg/dL\neGFR: >90 mL/min/1.73m² (normal kidney function)\nBUN: 7–20 mg/dL\nBUN/Creatinine Ratio: 10–20\nUric Acid: Men 3.4–7.0 mg/dL; Women 2.4–6.0 mg/dL\nSodium: 136–145 mEq/L\nPotassium: 3.5–5.0 mEq/L',
    highMeans: 'High creatinine and low eGFR indicate reduced kidney filtration — seen in CKD, acute kidney injury, dehydration, or nephritis. High uric acid causes gout and increases kidney stone risk.',
    lowMeans: 'Low potassium (hypokalaemia) can cause muscle weakness and heart rhythm problems. Low sodium (hyponatraemia) can cause confusion, headache, and seizures.',
    relatedTests: ['urine-routine', 'urine-microalbumin', 'urine-creatinine', 'ultrasound-kidneys', 'cystatin-c'],
    relatedDiseases: ['kidney-disease', 'diabetes', 'hypertension', 'arthritis'],
    faqs: [
      { question: 'What does a high creatinine level mean?', answer: 'High creatinine indicates the kidneys are not filtering blood efficiently. It can be caused by chronic kidney disease, acute kidney injury, dehydration, or high muscle mass.' },
      { question: 'What is eGFR and what does it mean?', answer: 'eGFR (estimated Glomerular Filtration Rate) measures how much blood your kidneys filter per minute. Normal is above 90 mL/min. eGFR 60–89: Mild kidney disease; 30–59: Moderate; 15–29: Severe; below 15: Kidney failure.' },
      { question: 'What is the KFT test cost in Bengaluru?', answer: 'At QXL Diagnostics, the Kidney Function Test costs ₹450 with free home collection across Bengaluru.' },
      { question: 'Can kidney disease occur without symptoms?', answer: 'Yes. CKD (Chronic Kidney Disease) is often completely silent until over 60–70% of kidney function is lost. Regular KFT screening is the only way to detect it early in high-risk groups.' },
      { question: 'What is the difference between KFT and urine microalbumin?', answer: 'KFT measures blood markers of kidney function; urine microalbumin detects small amounts of protein in urine — an early, sensitive sign of diabetic kidney damage before creatinine levels rise.' },
    ],
    keywords: ['kidney function test Bengaluru', 'KFT test price Bangalore', 'creatinine test Bengaluru', 'CKD test Bangalore', 'renal function test Bengaluru'],
    bodyPart: 'Kidneys',
    alternateNames: ['Renal Function Test', 'RFT', 'Kidney Panel', 'Renal Profile'],
  },
  {
    slug: 'vitamin-b12',
    name: 'Vitamin B12 Test (Cobalamin)',
    shortName: 'Vitamin B12',
    price: 600,
    originalPrice: 1200,
    department: 'Biochemistry',
    category: 'Vitamins & Nutrition',
    sampleType: 'Blood (serum)',
    fastingRequired: false,
    turnaround: 'Same Day',
    metaTitle: 'Vitamin B12 Test in Bengaluru — Price, Normal Range & Symptoms | QXL Diagnostics',
    metaDescription: 'Book Vitamin B12 test at QXL Diagnostics Bengaluru. NABL certified. ₹600. Detects B12 deficiency causing nerve damage, anaemia & fatigue. Free home collection.',
    heroDescription: 'Vitamin B12 deficiency is extremely common in India — especially in vegetarians and vegans — and causes irreversible nerve damage if untreated. The Vitamin B12 test detects this critical deficiency early.',
    whatIs: 'Vitamin B12 (Cobalamin) is a water-soluble vitamin essential for nerve function, DNA synthesis, and red blood cell formation. The human body cannot produce B12 — it must be obtained from animal products (meat, fish, eggs, dairy) or supplements.\n\nB12 deficiency is extremely prevalent in India:\n- Vegetarians and vegans: Very high risk (plant foods contain virtually no B12)\n- Over 80% of vegetarians in some Indian studies showed low B12 levels\n- People over 60: Reduced absorption from stomach acid decline\n- Metformin users: Metformin (diabetes drug) reduces B12 absorption by 30–50%',
    whyTaken: 'The Vitamin B12 test diagnoses:\n- B12 deficiency causing megaloblastic anaemia\n- Peripheral neuropathy (tingling, numbness in hands/feet) caused by B12 deficiency\n- Subacute combined degeneration of the spinal cord (severe, irreversible nerve damage)\n- Elevated homocysteine (B12 deficiency raises homocysteine — a cardiovascular risk factor)\n- Pernicious anaemia (autoimmune destruction of intrinsic factor needed for B12 absorption)',
    whoShouldTake: [
      'Vegetarians and vegans (especially those without B12 supplementation)',
      'People over 60 years (reduced absorption)',
      'Diabetics on metformin (drug reduces B12 absorption)',
      'Those with tingling or numbness in hands or feet',
      'People with unexplained fatigue or weakness',
      'Those with megaloblastic anaemia',
      'Pregnant women (B12 essential for fetal neural development)',
      'People who have had gastric surgery or have inflammatory bowel disease',
    ],
    preparation: [
      'No fasting required for Vitamin B12 test.',
      'If taking B12 supplements, inform your doctor — testing should ideally be done before starting supplementation or 48 hours after.',
      'No special preparation is needed.',
    ],
    procedure: 'A blood sample is collected and serum B12 is measured using Chemiluminescent Immunoassay (CLIA) — a highly accurate method. Results are available the same day.',
    normalRange: 'Severe deficiency: Below 100 pg/mL\nDeficiency: 100–200 pg/mL\nBorderline: 200–300 pg/mL\nNormal: 300–900 pg/mL\nElevated (rarely concerning): Above 900 pg/mL',
    highMeans: 'Very high B12 (above 1,000 pg/mL) can occasionally indicate liver disease, myeloproliferative disorders (polycythaemia vera, chronic myeloid leukaemia), or solid tumours. If extremely elevated without supplementation, further investigation may be needed.',
    lowMeans: 'Low B12 causes megaloblastic anaemia (large, abnormal red blood cells), peripheral neuropathy (tingling, numbness), cognitive impairment, depression, and in severe cases, irreversible spinal cord damage (subacute combined degeneration).',
    relatedTests: ['complete-blood-count', 'folate', 'homocysteine', 'methylmalonic-acid'],
    relatedDiseases: ['anemia', 'vitamin-deficiency'],
    faqs: [
      { question: 'What are the symptoms of Vitamin B12 deficiency?', answer: 'Symptoms include fatigue, weakness, tingling or numbness in hands and feet, difficulty walking, memory problems, depression, pale skin, and sore tongue.' },
      { question: 'What is a normal Vitamin B12 level?', answer: 'Normal B12 is 300–900 pg/mL. Levels below 200 pg/mL indicate deficiency; 200–300 pg/mL is borderline and should be monitored or treated if symptomatic.' },
      { question: 'What is the B12 test cost in Bengaluru?', answer: 'At QXL Diagnostics, the Vitamin B12 test costs ₹600 with free home collection across Bengaluru.' },
      { question: 'Which foods contain Vitamin B12?', answer: 'B12 is found almost exclusively in animal products: meat, fish, eggs, and dairy. Fortified foods (breakfast cereals, nutritional yeast) and supplements are the only reliable B12 sources for vegetarians and vegans.' },
      { question: 'How quickly does B12 deficiency nerve damage develop?', answer: 'Nerve damage (neuropathy) can develop within months to years of severe B12 deficiency. Early treatment prevents progression; severe deficiency can cause irreversible nerve damage — making early detection critical.' },
    ],
    keywords: ['Vitamin B12 test Bengaluru', 'B12 deficiency test Bangalore', 'cobalamin test price Bengaluru', 'B12 test vegetarian', 'nerve damage B12 test Bangalore'],
    bodyPart: 'Blood / Nervous System',
    alternateNames: ['Cobalamin', 'Cyanocobalamin', 'Serum B12'],
  },
  {
    slug: 'ana-profile',
    name: 'ANA Profile (Anti-Nuclear Antibody Profile)',
    shortName: 'ANA Profile',
    price: 2500,
    originalPrice: 5000,
    department: 'Immunology',
    category: 'Autoimmune',
    sampleType: 'Blood (serum)',
    fastingRequired: false,
    turnaround: '24–48 Hours',
    metaTitle: 'ANA Profile Test in Bengaluru — Autoimmune Test Price & Normal Range | QXL Diagnostics',
    metaDescription: 'Book ANA Profile (Anti-Nuclear Antibody) test at QXL Diagnostics Bengaluru. NABL certified. ₹2,500. Diagnoses lupus, rheumatoid arthritis, Sjögren\'s, scleroderma & other autoimmune diseases.',
    heroDescription: 'The ANA Profile is the most comprehensive blood test for diagnosing autoimmune diseases including lupus (SLE), rheumatoid arthritis, Sjögren\'s syndrome, and scleroderma.',
    whatIs: 'The ANA Profile (Anti-Nuclear Antibody Profile) is a comprehensive immunology panel that tests for multiple specific antibodies that the immune system mistakenly makes against the body\'s own cells (autoantibodies). It includes:\n- **ANA by IFA**: Screening test using indirect immunofluorescence\n- **Anti-dsDNA**: Highly specific for lupus (SLE)\n- **Anti-Sm**: Very specific for lupus\n- **Anti-SSA/Ro and Anti-SSB/La**: Sjögren\'s syndrome\n- **Anti-Scl-70**: Scleroderma\n- **Anti-Jo-1**: Inflammatory myositis\n- **Anti-Histone**: Drug-induced lupus\n- **Anti-Centromere**: Limited scleroderma (CREST syndrome)\n- **Anti-U1 RNP**: Mixed connective tissue disease\n- **Anti-Ribosomal P**: Lupus with neuropsychiatric involvement\n\nQXL Diagnostics performs the ANA Profile using Line Immunoassay (LIA) — the gold standard method that detects 16+ specific autoantibodies simultaneously.',
    whyTaken: 'The ANA Profile is used to:\n- Diagnose autoimmune diseases: lupus (SLE), Sjögren\'s syndrome, scleroderma, mixed connective tissue disease, polymyositis/dermatomyositis\n- Differentiate between different autoimmune conditions (specific antibodies point to specific diseases)\n- Monitor disease activity in known autoimmune patients\n- Investigate unexplained joint pain, rash, fatigue, or kidney involvement',
    whoShouldTake: [
      'People with joint pain, swelling, or morning stiffness without clear cause',
      'Those with butterfly facial rash or photosensitivity',
      'Women with recurrent pregnancy loss',
      'Patients with unexplained kidney disease or blood cell abnormalities',
      'Those with dry eyes and dry mouth (Sjögren\'s)',
      'People with skin thickening or tightening (scleroderma)',
      'Individuals with muscle weakness and skin rash (dermatomyositis)',
      'Those with Raynaud\'s phenomenon (fingers turning white/blue in cold)',
    ],
    preparation: [
      'No fasting required.',
      'Inform your doctor about all medications — some drugs can cause positive ANA results (drug-induced lupus).',
      'No special preparation needed.',
    ],
    procedure: 'A blood sample is collected. At QXL Diagnostics, the ANA Profile is performed using Line Immunoassay (LIA) which simultaneously detects 16+ specific autoantibodies with high accuracy. This is combined with ANA screening by Indirect Immunofluorescence (IIF) on HEp-2 cells, which gives the titre and pattern of the antibody.',
    normalRange: 'ANA by IFA: Negative (titre <1:80)\nAnti-dsDNA: Negative (<10 IU/mL)\nAll specific antibodies: Negative\n\nNote: A positive ANA does not always mean autoimmune disease — 5–15% of healthy individuals can have low-positive ANA. Specific antibody patterns determine clinical significance.',
    highMeans: 'Positive anti-dsDNA: Strongly suggests lupus (SLE).\nPositive anti-SSA/SSB: Sjögren\'s syndrome.\nPositive anti-Scl-70: Scleroderma.\nPositive anti-Jo-1: Inflammatory myositis.\nHigh ANA titre (>1:320): More likely to be clinically significant.',
    lowMeans: 'Negative ANA essentially rules out most autoimmune connective tissue diseases. A negative result in a symptomatic patient may prompt testing for other conditions (seronegative arthritis, fibromyalgia).',
    relatedTests: ['rheumatoid-factor', 'anti-ccp', 'complement-c3-c4', 'esr', 'crp', 'complete-blood-count', 'urine-routine'],
    relatedDiseases: ['autoimmune-diseases', 'arthritis'],
    faqs: [
      { question: 'What does a positive ANA test mean?', answer: 'A positive ANA means your immune system has made antibodies against your own cells. However, 5–15% of healthy people can have a low-positive ANA. The significance depends on the titre (strength) and specific antibody pattern, interpreted alongside your symptoms.' },
      { question: 'What diseases does ANA profile detect?', answer: 'ANA Profile detects lupus (SLE), Sjögren\'s syndrome, scleroderma, mixed connective tissue disease, polymyositis, dermatomyositis, and drug-induced lupus.' },
      { question: 'What is the ANA Profile test cost in Bengaluru?', answer: 'At QXL Diagnostics, the ANA Profile costs ₹2,500 with free home collection across Bengaluru.' },
      { question: 'Is ANA test same as ENA profile?', answer: 'No. ANA (Anti-Nuclear Antibody) is the screening test. ENA Profile (Extractable Nuclear Antigen) is a more specific follow-up test that identifies which specific autoantibody is present (Sm, SSA, SSB, Scl-70, Jo-1, etc.).' },
      { question: 'How long does ANA Profile test take?', answer: 'The ANA Profile by LIA typically takes 24–48 hours for full results, as it is a complex immunology test requiring careful analysis.' },
    ],
    keywords: ['ANA test Bengaluru', 'autoimmune test Bangalore', 'ANA profile price Bengaluru', 'lupus test Bengaluru', 'anti-nuclear antibody test Bangalore'],
    bodyPart: 'Blood / Immune System',
    alternateNames: ['Anti-Nuclear Antibody Profile', 'ANA Panel', 'Autoimmune Profile'],
  },
  {
    slug: 'ferritin',
    name: 'Ferritin Test (Serum Ferritin)',
    shortName: 'Ferritin',
    price: 500,
    originalPrice: 1000,
    department: 'Biochemistry',
    category: 'Anaemia & Iron',
    sampleType: 'Blood (serum)',
    fastingRequired: false,
    turnaround: 'Same Day',
    metaTitle: 'Ferritin Test in Bengaluru — Serum Ferritin Price, Normal Range & What It Means | QXL Diagnostics',
    metaDescription: 'Book Serum Ferritin test at QXL Diagnostics Bengaluru. NABL certified. ₹500. Detects iron deficiency anaemia before haemoglobin drops. Free home collection.',
    heroDescription: 'Serum Ferritin is the most sensitive test for iron deficiency — it detects depleted iron stores before haemoglobin drops, making it essential for diagnosing early iron deficiency anaemia.',
    whatIs: 'Ferritin is a protein that stores iron in your cells. Serum Ferritin measures the amount of stored iron in your body — the most sensitive indicator of your body\'s total iron stores.\n\nWhile haemoglobin (measured in a CBC) only falls when iron deficiency is already moderate-to-severe, ferritin drops much earlier — making it the best early warning sign of iron deficiency before anaemia fully develops.',
    whyTaken: 'The Ferritin test is used to:\n- Diagnose iron deficiency anaemia (the most common nutritional deficiency worldwide)\n- Differentiate anaemia causes: iron deficiency vs. chronic disease vs. B12/folate deficiency\n- Monitor iron supplementation response\n- Investigate hair loss (ferritin below 70 ng/mL is associated with hair fall)\n- Assess iron overload (haemochromatosis)\n- Evaluate elevated ferritin as an inflammation/infection marker',
    whoShouldTake: [
      'Women with heavy menstrual bleeding',
      'Pregnant women (iron demands increase dramatically)',
      'Vegetarians and vegans (plant iron is poorly absorbed)',
      'People with unexplained fatigue, weakness, or shortness of breath',
      'Those with restless leg syndrome (often linked to low ferritin)',
      'People with hair loss (low ferritin is a common, overlooked cause)',
      'Blood donors and athletes (higher iron losses)',
      'Infants and toddlers (high growth-related iron demands)',
    ],
    preparation: [
      'No fasting required for ferritin test.',
      'If being tested alongside a full iron panel, fasting for 4–8 hours may be recommended.',
      'Ferritin is an acute phase reactant — it rises during infections and inflammation, which can mask iron deficiency. If you are currently ill, inform your doctor.',
    ],
    procedure: 'A blood sample is collected and serum ferritin is measured using Chemiluminescent Immunoassay (CLIA). Results are usually available the same day.',
    normalRange: 'Men: 24–336 ng/mL\nWomen: 11–307 ng/mL\nChildren (6 months–15 years): 7–140 ng/mL\n\nFor hair health and energy: many experts recommend ferritin above 50–70 ng/mL\nFor restless leg syndrome: ferritin above 75 ng/mL',
    highMeans: 'High ferritin (above 300 in men, above 200 in women) can indicate: iron overload (haemochromatosis), liver disease, chronic inflammation, infection, rheumatoid arthritis, adult-onset Still\'s disease, or certain cancers. Very high ferritin (>1,000) in a sick patient is a red flag for serious infection, haemophagocytic lymphohistiocytosis (HLH), or Still\'s disease.',
    lowMeans: 'Low ferritin is the most reliable indicator of depleted iron stores — the earliest sign of iron deficiency, preceding anaemia. It is associated with fatigue, reduced exercise tolerance, hair loss, restless legs, and impaired immune function.',
    relatedTests: ['complete-blood-count', 'iron-studies', 'transferrin-saturation', 'tibbc', 'vitamin-b12'],
    relatedDiseases: ['anemia'],
    faqs: [
      { question: 'What is a normal ferritin level?', answer: 'Normal ferritin is 24–336 ng/mL for men and 11–307 ng/mL for women. For hair health and energy, many experts recommend levels above 50–70 ng/mL.' },
      { question: 'Can low ferritin cause hair loss?', answer: 'Yes. Ferritin below 30–70 ng/mL is strongly associated with telogen effluvium (diffuse hair loss). Correcting iron deficiency often significantly reduces hair fall.' },
      { question: 'What is the ferritin test cost in Bengaluru?', answer: 'At QXL Diagnostics, serum ferritin costs ₹500 with free home collection across Bengaluru.' },
      { question: 'What causes high ferritin?', answer: 'High ferritin can be caused by iron overload (haemochromatosis), liver disease (hepatitis, fatty liver, cirrhosis), chronic inflammation (rheumatoid arthritis, IBD), infections, and certain cancers. It needs evaluation alongside other tests.' },
      { question: 'What is the difference between ferritin and haemoglobin?', answer: 'Haemoglobin measures oxygen-carrying capacity of red blood cells — it only falls in moderate-to-severe iron deficiency. Ferritin measures iron stores and falls much earlier, detecting iron deficiency before anaemia develops.' },
    ],
    keywords: ['ferritin test Bengaluru', 'serum ferritin price Bangalore', 'iron deficiency test Bengaluru', 'hair loss test Bangalore ferritin', 'anaemia test Bengaluru'],
    bodyPart: 'Blood / Bone Marrow',
    alternateNames: ['Serum Ferritin', 'Iron Storage Protein', 'Ferritin Level'],
  },
  {
    slug: 'troponin',
    name: 'Troponin I Test (High Sensitivity)',
    shortName: 'Troponin I',
    price: 1200,
    originalPrice: 2500,
    department: 'Biochemistry',
    category: 'Cardiology',
    sampleType: 'Blood (serum)',
    fastingRequired: false,
    turnaround: '2–4 Hours',
    metaTitle: 'Troponin Test in Bengaluru — Heart Attack Test Price & Normal Range | QXL Diagnostics',
    metaDescription: 'Book High-Sensitivity Troponin I test at QXL Diagnostics Bengaluru. NABL certified. ₹1,200. Emergency heart attack diagnosis. 2–4 hour results. 24/7 home collection.',
    heroDescription: 'High-Sensitivity Troponin I is the gold standard emergency test for diagnosing heart attacks (myocardial infarction) — detecting heart muscle damage within 1–3 hours of onset.',
    whatIs: 'Troponin is a protein found inside heart muscle cells (cardiomyocytes). When heart muscle is damaged — as in a heart attack — troponin leaks into the bloodstream. High-Sensitivity Troponin I (hs-TnI) can detect even tiny amounts of troponin, making it the most accurate test for:\n\n- Diagnosing acute myocardial infarction (heart attack) within 1–3 hours\n- Ruling out heart attack in chest pain patients (negative predictive value >99%)\n- Stratifying risk in patients with unstable angina\n\nQXL Diagnostics uses 5th generation High-Sensitivity Troponin I assay — the most accurate currently available.',
    whyTaken: 'Troponin I is tested to:\n- Diagnose or rule out heart attack in patients with chest pain\n- Assess myocarditis (heart muscle inflammation)\n- Evaluate cardiac stress in critically ill patients\n- Monitor heart damage from chemotherapy\n- Diagnose other causes of heart muscle injury (pulmonary embolism, severe sepsis)',
    whoShouldTake: [
      'Anyone with chest pain, tightness, or pressure',
      'People with left arm pain, jaw pain, or shoulder pain',
      'Those with sudden breathlessness or extreme fatigue',
      'Patients with nausea, sweating, or dizziness — possible atypical heart attack symptoms',
      'Diabetics and women may present with atypical symptoms — any unexplained discomfort warrants testing',
    ],
    preparation: [
      'No fasting required.',
      'The test is most useful when repeated at 0 and 3 hours (serial testing) to detect rising or falling troponin levels.',
      'Seek emergency care if symptoms suggest heart attack — do not delay testing.',
    ],
    procedure: 'A blood sample is collected and processed urgently. QXL Diagnostics provides priority processing for Troponin, with results in 2–4 hours. Serial testing at 0 and 3 hours (0h/3h protocol) is recommended for chest pain evaluation.',
    normalRange: 'hs-Troponin I: Below 16 ng/L (women); Below 34 ng/L (men) — exact values vary by assay generation and manufacturer. Results above the 99th percentile indicate myocardial injury.',
    highMeans: 'Rising troponin (two serial measurements at 0 and 3 hours) with symptoms = Acute myocardial infarction (heart attack). Single high troponin without symptoms may indicate myocarditis, pulmonary embolism, heart failure, sepsis, or chronic kidney disease.',
    lowMeans: 'A consistently normal troponin at 0 and 3 hours has a >99% negative predictive value for ruling out heart attack in low-to-intermediate risk patients with chest pain.',
    relatedTests: ['ck-mb', 'nt-probnp', 'bnp', 'ecg', 'd-dimer', 'hs-crp'],
    relatedDiseases: ['heart-disease'],
    faqs: [
      { question: 'What does a positive troponin result mean?', answer: 'A high troponin indicates heart muscle damage. Combined with symptoms and serial testing, it is diagnostic of a heart attack. However, elevated troponin can also occur with myocarditis, pulmonary embolism, or severe sepsis.' },
      { question: 'How quickly does troponin rise after a heart attack?', answer: 'Troponin starts rising 1–3 hours after heart muscle damage begins, peaks at 12–24 hours, and can remain elevated for 1–2 weeks — allowing diagnosis even days after a heart attack.' },
      { question: 'What is the Troponin test cost in Bengaluru?', answer: 'At QXL Diagnostics, High-Sensitivity Troponin I costs ₹1,200 with priority processing and results in 2–4 hours.' },
      { question: 'Can stress cause elevated troponin?', answer: 'Severe physical or emotional stress can cause stress cardiomyopathy (Takotsubo syndrome) which elevates troponin. However, "stress" from ordinary anxiety does not significantly raise troponin.' },
      { question: 'Is one troponin test enough to rule out a heart attack?', answer: 'No. A single negative troponin does not rule out a heart attack. Serial testing at 0 and 3 hours (0h/3h rapid rule-out protocol) is needed for reliable exclusion of MI.' },
    ],
    keywords: ['troponin test Bengaluru', 'heart attack test Bangalore', 'troponin I price Bengaluru', 'cardiac enzyme test Bangalore', 'chest pain blood test Bengaluru'],
    bodyPart: 'Heart',
    alternateNames: ['Troponin I', 'Cardiac Troponin', 'hs-TnI', 'High Sensitivity Troponin'],
  },
  {
    slug: 'hs-crp',
    name: 'hs-CRP Test (High Sensitivity C-Reactive Protein)',
    shortName: 'hs-CRP',
    price: 500,
    originalPrice: 1000,
    department: 'Biochemistry',
    category: 'Inflammation & Cardiology',
    sampleType: 'Blood (serum)',
    fastingRequired: false,
    turnaround: 'Same Day',
    metaTitle: 'hs-CRP Test in Bengaluru — Inflammation & Heart Risk Test Price | QXL Diagnostics',
    metaDescription: 'Book hs-CRP (High Sensitivity CRP) test at QXL Diagnostics Bengaluru. NABL certified. ₹500. Measures inflammation to predict heart attack and stroke risk. Free home collection.',
    heroDescription: 'The hs-CRP test measures low-level inflammation in the body — a powerful predictor of future heart attack and stroke risk, even when cholesterol levels appear normal.',
    whatIs: 'C-Reactive Protein (CRP) is a protein produced by the liver in response to inflammation. High-Sensitivity CRP (hs-CRP) measures very low levels of CRP that standard CRP tests cannot detect.\n\nhs-CRP is a cardiovascular risk marker — even mild chronic inflammation (as detected by hs-CRP) is associated with a significantly increased risk of heart attack and stroke, independent of cholesterol levels. The hs-CRP test helps identify high-risk individuals who may need more aggressive prevention.',
    whyTaken: 'The hs-CRP test is used to:\n- Assess cardiovascular risk in patients with intermediate cholesterol/risk levels\n- Guide statin therapy decisions (JUPITER trial showed hs-CRP-guided statin treatment reduced heart events)\n- Monitor chronic inflammatory conditions (RA, IBD, lupus)\n- Evaluate infection severity\n- Assess metabolic syndrome and insulin resistance\n- Monitor recovery from surgery or infection',
    whoShouldTake: [
      'Adults with intermediate cardiovascular risk (borderline cholesterol)',
      'Diabetics (chronic low-grade inflammation is common)',
      'People with metabolic syndrome or obesity',
      'Smokers (smoking causes chronic inflammation)',
      'People with family history of early heart disease',
      'Those with autoimmune conditions (for monitoring)',
      'Individuals planning preventive cardiovascular screening',
    ],
    preparation: [
      'No fasting required.',
      'Avoid testing during active infection, recent surgery, or injury — these cause very high CRP and cannot be interpreted for cardiovascular risk.',
      'Ideally test when you are completely well (no cold, flu, or other illness in past 2 weeks).',
    ],
    procedure: 'A blood sample is collected and hs-CRP is measured using a highly sensitive immunoturbidimetric or nephelometric method capable of detecting CRP as low as 0.1 mg/L.',
    normalRange: 'Cardiovascular risk categories:\nLow risk: <1.0 mg/L\nAverage risk: 1.0–3.0 mg/L\nHigh risk: >3.0 mg/L\n\nFor general inflammation: >10 mg/L suggests significant infection or inflammation (not primarily cardiovascular).',
    highMeans: 'Persistently high hs-CRP (above 3 mg/L) significantly increases cardiovascular risk. Very high CRP (above 10 mg/L) indicates active infection or inflammation that needs separate evaluation.',
    lowMeans: 'Low hs-CRP (below 1 mg/L) indicates low cardiovascular risk from inflammation. This is the desirable range.',
    relatedTests: ['lipid-profile', 'hba1c', 'complete-blood-count', 'esr', 'interleukin-6'],
    relatedDiseases: ['heart-disease', 'diabetes', 'arthritis'],
    faqs: [
      { question: 'What is the difference between CRP and hs-CRP?', answer: 'Standard CRP detects high levels of inflammation (>10 mg/L) in infections and acute illness. hs-CRP is 100× more sensitive and detects low-grade chronic inflammation (0.1–10 mg/L) that predicts cardiovascular risk.' },
      { question: 'What is a normal hs-CRP level?', answer: 'For cardiovascular risk assessment: below 1 mg/L is low risk; 1–3 mg/L is average risk; above 3 mg/L is high risk for heart events.' },
      { question: 'What is the hs-CRP test cost in Bengaluru?', answer: 'At QXL Diagnostics, the hs-CRP test costs ₹500 with free home collection across Bengaluru.' },
      { question: 'Does hs-CRP detect cancer?', answer: 'hs-CRP is a non-specific marker of inflammation. While very high CRP can be associated with some cancers, it is not a cancer screening test. Specific cancer markers (PSA, CA-125, CEA) are used for cancer screening.' },
      { question: 'Can lifestyle changes lower hs-CRP?', answer: 'Yes. Regular exercise, Mediterranean diet, weight loss, quitting smoking, and treating diabetes all significantly reduce hs-CRP levels and cardiovascular risk.' },
    ],
    keywords: ['hs-CRP test Bengaluru', 'inflammation test Bangalore', 'heart risk test Bengaluru', 'high sensitivity CRP Bangalore', 'CRP test price Bengaluru'],
    bodyPart: 'Blood / Cardiovascular',
    alternateNames: ['High Sensitivity CRP', 'Cardiac CRP', 'hsCRP', 'Ultra-Sensitive CRP'],
  },
  {
    slug: 'psa',
    name: 'PSA Test (Prostate-Specific Antigen)',
    shortName: 'PSA',
    price: 600,
    originalPrice: 1200,
    department: 'Biochemistry',
    category: 'Cancer Markers',
    sampleType: 'Blood (serum)',
    fastingRequired: false,
    turnaround: 'Same Day',
    metaTitle: 'PSA Test in Bengaluru — Prostate Cancer Screening Price & Normal Range | QXL Diagnostics',
    metaDescription: 'Book PSA (Prostate-Specific Antigen) test at QXL Diagnostics Bengaluru. NABL certified. ₹600. Prostate cancer screening for men over 50. Free home collection.',
    heroDescription: 'The PSA test is the most important prostate cancer screening blood test for men over 50 — enabling early detection when treatment is most effective.',
    whatIs: 'Prostate-Specific Antigen (PSA) is a protein produced by both normal and cancerous prostate cells. A blood PSA test measures the amount of PSA in your bloodstream.\n\nPSA is primarily used for prostate cancer screening and monitoring. While PSA can be elevated in non-cancerous conditions (BPH, prostatitis), persistently high or rising PSA warrants further investigation with a urologist.',
    whyTaken: 'PSA testing is used for:\n- Prostate cancer screening in men over 50\n- High-risk screening from age 40 (family history, African descent)\n- Monitoring response to prostate cancer treatment\n- Detecting cancer recurrence after treatment\n- Evaluating benign prostatic hyperplasia (BPH)',
    whoShouldTake: [
      'All men above 50 years (annual screening)',
      'Men above 40 with family history of prostate cancer (father or brother)',
      'Men of African descent (higher risk group) — from age 40',
      'Men with urinary symptoms (weak stream, frequency, nocturia, incomplete emptying)',
      'Men under active surveillance for prostate cancer',
    ],
    preparation: [
      'No fasting required.',
      'Avoid sexual activity for 24–48 hours before the test (ejaculation temporarily raises PSA).',
      'Avoid vigorous cycling or prostate massage for 24–48 hours before the test.',
      'Inform your doctor if you have recently had a prostate biopsy, cystoscopy, or UTI — these elevate PSA.',
      'Take the test before a digital rectal exam, not after.',
    ],
    procedure: 'A blood sample is collected and Total PSA (and optionally Free PSA) is measured using chemiluminescent immunoassay.',
    normalRange: 'Age-adjusted PSA levels:\nAge 40–49: Below 2.5 ng/mL\nAge 50–59: Below 3.5 ng/mL\nAge 60–69: Below 4.5 ng/mL\nAge 70+: Below 6.5 ng/mL\n\nPSA Velocity (rising by >0.75 ng/mL per year) is concerning even within normal range.',
    highMeans: 'Elevated PSA above age-adjusted normal range may indicate prostate cancer, benign prostatic hyperplasia (BPH), prostatitis, or recent procedures. A single high PSA does not diagnose cancer — a urologist will recommend digital rectal exam (DRE) and possibly prostate biopsy.',
    lowMeans: 'A low PSA provides reassurance against prostate cancer. However, some aggressive prostate cancers can occur with normal PSA (especially Gleason grade 4/5 tumours).',
    relatedTests: ['free-psa', 'phi', 'prostate-4k-score'],
    relatedDiseases: ['cancer-screening'],
    faqs: [
      { question: 'What is a normal PSA level?', answer: 'Normal PSA depends on age: below 2.5 ng/mL for men 40–49; below 3.5 for men 50–59; below 4.5 for men 60–69. PSA above 4.0 ng/mL in men under 70 generally prompts further evaluation.' },
      { question: 'Can PSA test diagnose prostate cancer?', answer: 'PSA is a screening test, not a diagnostic test. An elevated PSA can be caused by prostate cancer, BPH, or prostatitis. Definitive diagnosis requires prostate biopsy.' },
      { question: 'What is the PSA test cost in Bengaluru?', answer: 'At QXL Diagnostics, the PSA test costs ₹600 with free home collection across Bengaluru.' },
      { question: 'At what age should men start PSA screening?', answer: 'Average-risk men: age 50. High-risk men (family history of prostate cancer, African descent): age 40–45. Discuss with your doctor about benefits and limitations of PSA screening.' },
      { question: 'What if my PSA is elevated?', answer: 'An elevated PSA does not automatically mean cancer. Your doctor will consider the pattern (PSA velocity, free/total PSA ratio), risk factors, and may recommend a digital rectal exam or prostate MRI before biopsy.' },
    ],
    keywords: ['PSA test Bengaluru', 'prostate cancer test Bangalore', 'PSA test price Bengaluru', 'prostate cancer screening Bangalore', 'PSA test men Bengaluru'],
    bodyPart: 'Prostate',
    alternateNames: ['Prostate-Specific Antigen', 'Total PSA', 'Prostate Cancer Marker'],
  },
  {
    slug: 'dengue-ns1-antigen',
    name: 'Dengue NS1 Antigen & Antibody Test',
    shortName: 'Dengue Test',
    price: 800,
    originalPrice: 1500,
    department: 'Microbiology / Serology',
    category: 'Infectious Diseases',
    sampleType: 'Blood (serum)',
    fastingRequired: false,
    turnaround: 'Same Day',
    metaTitle: 'Dengue Test in Bengaluru — NS1 Antigen Price & Same-Day Report | QXL Diagnostics',
    metaDescription: 'Book Dengue NS1 Antigen + IgM/IgG Antibody test at QXL Diagnostics Bengaluru. NABL certified. ₹800. Same-day results. Diagnose dengue fever quickly. Free home collection.',
    heroDescription: 'The Dengue NS1 Antigen test detects dengue virus directly in blood during early infection (days 1–5 of fever) — providing same-day results when treatment decisions are most critical.',
    whatIs: 'Dengue fever is caused by the dengue virus (DENV), transmitted by Aedes aegypti mosquitoes. Diagnosis requires different tests depending on the stage of illness:\n\n- **Dengue NS1 Antigen**: Detects the dengue virus protein directly in blood — most accurate in days 1–5 of fever (early infection)\n- **Dengue IgM Antibody**: Appears 5–7 days after fever onset — indicates current or recent infection\n- **Dengue IgG Antibody**: Appears later and can persist for months/years — indicates past infection (protective or increases risk of severe dengue in secondary infection)\n\nQXL Diagnostics performs the complete Dengue combo test (NS1 + IgM + IgG) for comprehensive diagnosis at any stage of illness.',
    whyTaken: 'Dengue testing is needed for:\n- Diagnosing dengue fever in patients with high fever (>38.5°C), severe headache, eye pain, joint/muscle pain, and/or rash\n- Guiding clinical management (monitoring platelet count)\n- Identifying high-risk patients (low platelet count = dengue haemorrhagic fever risk)\n- Ruling out dengue in patients from endemic areas during monsoon season\n- Distinguishing dengue from malaria, typhoid, and other tropical fevers',
    whoShouldTake: [
      'Anyone with sudden high fever (≥38.5°C) in Bengaluru during monsoon/post-monsoon season (July–November)',
      'People with severe headache, pain behind eyes, or rash during fever',
      'Those with joint or muscle pain during fever',
      'Patients with nausea, vomiting, or skin bleeding during fever',
      'Those who have returned from travel to dengue-endemic areas',
    ],
    preparation: [
      'No fasting required.',
      'Ideally test on day 1–5 of fever for best NS1 Antigen sensitivity.',
      'Inform your doctor about fever onset date so the correct test is selected.',
    ],
    procedure: 'Blood is collected and tested for NS1 antigen and IgM/IgG antibodies using rapid immunochromatographic assay and/or ELISA. QXL Diagnostics also performs serial platelet counts to monitor dengue severity.',
    normalRange: 'NS1 Antigen: Negative\nDengue IgM: Negative\nDengue IgG: Negative (or positive for past infection)\n\nA positive result in a febrile patient with typical symptoms confirms dengue.',
    highMeans: 'Positive NS1 antigen confirms active dengue virus infection in early fever stages. The severity of dengue (mild dengue, dengue haemorrhagic fever, dengue shock syndrome) is assessed by platelet count and clinical signs rather than by the antigen test alone.',
    lowMeans: 'Negative NS1 and antibody results in a febrile patient largely rule out dengue. Consider other tropical fevers (malaria, typhoid, chikungunya, leptospirosis).',
    relatedTests: ['complete-blood-count', 'malaria-antigen', 'typhoid-widal', 'chikungunya-antibody'],
    relatedDiseases: ['dengue', 'fever-evaluation'],
    faqs: [
      { question: 'What is the best time to test for dengue?', answer: 'Test on day 1–5 of fever for NS1 Antigen (most accurate in early infection). If fever started more than 5 days ago, IgM antibody testing is more useful.' },
      { question: 'What are the symptoms of dengue fever?', answer: 'Sudden high fever (38.5–41°C), severe headache, pain behind eyes, severe joint and muscle pain (break-bone fever), rash, and nausea/vomiting. Warning signs of severe dengue: abdominal pain, bleeding, difficulty breathing.' },
      { question: 'What is the dengue test cost in Bengaluru?', answer: 'At QXL Diagnostics, the Dengue NS1 + IgM/IgG combo test costs ₹800 with free home collection across Bengaluru.' },
      { question: 'How quickly can dengue test results be obtained?', answer: 'At QXL Diagnostics, dengue test results are available the same day. We prioritise dengue testing for febrile patients.' },
      { question: 'Is there a treatment for dengue fever?', answer: 'There is no specific antiviral treatment for dengue. Management is supportive: rest, hydration, paracetamol for fever (avoid ibuprofen/aspirin), and monitoring platelet count. Severe dengue may require hospitalisation.' },
    ],
    keywords: ['dengue test Bengaluru', 'dengue NS1 test price Bangalore', 'dengue fever test same day', 'dengue blood test Bengaluru monsoon', 'platelet count dengue Bengaluru'],
    bodyPart: 'Blood / Immune System',
    alternateNames: ['Dengue NS1 Antigen', 'Dengue Rapid Test', 'Dengue IgM IgG'],
  },
];

/** Get all test slugs for static generation */
export function getAllTestSlugs(): string[] {
  return TESTS_DATA.map(t => t.slug);
}

/** Get a single test by slug */
export function getTestBySlug(slug: string): TestData | undefined {
  return TESTS_DATA.find(t => t.slug === slug);
}

/** Group tests by category */
export function getTestsByCategory(): Record<string, TestData[]> {
  const grouped: Record<string, TestData[]> = {};
  for (const test of TESTS_DATA) {
    if (!grouped[test.category]) grouped[test.category] = [];
    grouped[test.category].push(test);
  }
  return grouped;
}
