import { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/locations/',
          '/specialities/',
          '/doctors/',
          '/packages/',
          '/conditions/',
          '/blog/',
          '/about',
          '/contact',
          '/centers',
          '/home-blood-collection-bangalore',
          '/diagnostic-lab-bangalore',
        ],
        disallow: [
          '/admin/',
          '/api/',
          '/login/',
          '/login',
          '/dashboard/',
          '/dashboard',
          '/profile/',
          '/profile',
          '/report/',
          '/report',
          '/book',
          '/book/',
          '/cart',
          '/cart/',
          '/checkout',
          '/checkout/',
          '/my-bookings',
          '/my-bookings/',
          '/my-reports',
          '/my-reports/',
          '/home',
          '/home/',
          '/payment-terms/',
          '/unsubscribe/',
        ],
      },
      // Welcome all major AI / search crawlers for GEO, AEO & AI-Search visibility.
      { userAgent: 'OAI-SearchBot', allow: '/' },
      { userAgent: 'Claude-SearchBot', allow: '/' },
      { userAgent: 'Claude-User', allow: '/' },
      { userAgent: 'PerplexityBot', allow: '/' },
      { userAgent: 'GPTBot', allow: '/' },
      { userAgent: 'ChatGPT-User', allow: '/' },
      { userAgent: 'ClaudeBot', allow: '/' },
      { userAgent: 'anthropic-ai', allow: '/' },
      { userAgent: 'Google-Extended', allow: '/' },
      { userAgent: 'Applebot-Extended', allow: '/' },
      { userAgent: 'Bytespider', allow: '/' },
      { userAgent: 'CCBot', allow: '/' },
      { userAgent: 'meta-externalagent', allow: '/' },
      // Gemini / Google AI crawlers
      { userAgent: 'Googlebot', allow: '/' },
      { userAgent: 'bingbot', allow: '/' },
      { userAgent: 'DuckDuckBot', allow: '/' },
    ],
    sitemap: 'https://qxldiagnostics.com/sitemap.xml',
    host: 'https://qxldiagnostics.com',
  };
}

