import React from 'react';
import { Shield } from 'lucide-react';

export const metadata = {
  title: 'Privacy Policy | QXL Diagnostics',
  description: 'Privacy Policy and data protection guidelines for QXL Diagnostics.',
  alternates: {
    canonical: 'https://qxldiagnostics.com/privacy-policy',
  },
};

export default function PrivacyPolicyPage() {
  return (
    <div className="bg-[#f8faff] min-h-screen py-16">
      <div className="max-w-[1000px] mx-auto px-4 w-full">
        <div className="bg-white rounded-3xl p-8 md:p-12 shadow-sm border border-gray-100">
          <div className="flex items-center gap-4 mb-8">
            <div className="w-12 h-12 bg-blue-50 rounded-xl flex items-center justify-center flex-shrink-0">
              <Shield className="w-6 h-6 text-[#2563eb]" />
            </div>
            <h1 className="text-3xl md:text-4xl font-extrabold text-[#0f2d5e]">Privacy Policy</h1>
          </div>
          
          <div className="prose prose-blue max-w-none text-slate-600">
            <p className="font-medium text-lg mb-8">Last Updated: June 2026</p>

            <h2 className="text-2xl font-bold text-[#0f2d5e] mt-8 mb-4">1. Introduction</h2>
            <p className="mb-4">
              Welcome to QXL Diagnostics. We respect your privacy and are committed to protecting your personal data. This privacy policy will inform you as to how we look after your personal data when you visit our website (regardless of where you visit it from) or use our diagnostic services and tell you about your privacy rights and how the law protects you.
            </p>

            <h2 className="text-2xl font-bold text-[#0f2d5e] mt-8 mb-4">2. The Data We Collect About You</h2>
            <p className="mb-4">
              Personal data, or personal information, means any information about an individual from which that person can be identified. We may collect, use, store and transfer different kinds of personal data about you which we have grouped together as follows:
            </p>
            <ul className="list-disc pl-6 mb-4 space-y-2">
              <li><strong>Identity Data</strong> includes first name, maiden name, last name, username or similar identifier, marital status, title, date of birth and gender.</li>
              <li><strong>Contact Data</strong> includes billing address, home collection address, email address and telephone numbers.</li>
              <li><strong>Health Data</strong> includes medical history, symptoms, test prescriptions, and diagnostic test results generated by our laboratories.</li>
              <li><strong>Financial Data</strong> includes bank account and payment card details for transaction purposes.</li>
            </ul>

            <h2 className="text-2xl font-bold text-[#0f2d5e] mt-8 mb-4">3. How We Use Your Personal Data</h2>
            <p className="mb-4">
              We will only use your personal data when the law allows us to. Most commonly, we will use your personal data in the following circumstances:
            </p>
            <ul className="list-disc pl-6 mb-4 space-y-2">
              <li>To register you as a new patient or customer.</li>
              <li>To process and deliver your diagnostic test orders, including home sample collection.</li>
              <li>To communicate your diagnostic reports to you and your authorized healthcare providers.</li>
              <li>To manage our relationship with you, including asking you to leave a review or take a survey.</li>
            </ul>

            <h2 className="text-2xl font-bold text-[#0f2d5e] mt-8 mb-4">4. Data Security</h2>
            <p className="mb-4">
              We have put in place appropriate security measures to prevent your personal data from being accidentally lost, used, or accessed in an unauthorized way, altered, or disclosed. In addition, we limit access to your personal data to those employees, agents, contractors, and other third parties who have a business or medical need to know. They will only process your personal data on our instructions and they are subject to a duty of confidentiality.
            </p>

            <h2 className="text-2xl font-bold text-[#0f2d5e] mt-8 mb-4">5. Contact Us</h2>
            <p className="mb-4">
              If you have any questions about this privacy policy or our privacy practices, please contact us at:
            </p>
            <p className="mb-4 font-medium">
              QXL Diagnostics<br />
              Email: qxldiagnostics@gmail.com<br />
              Phone: +91 9964 639639
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
