import React from 'react';
import { FileText } from 'lucide-react';

export const metadata = {
  title: 'Terms of Use | QXL Diagnostics',
  description: 'Terms of Use and service conditions for QXL Diagnostics.',
};

export default function TermsOfUsePage() {
  return (
    <div className="bg-[#f8faff] min-h-screen py-16">
      <div className="max-w-[1000px] mx-auto px-4 w-full">
        <div className="bg-white rounded-3xl p-8 md:p-12 shadow-sm border border-gray-100">
          <div className="flex items-center gap-4 mb-8">
            <div className="w-12 h-12 bg-blue-50 rounded-xl flex items-center justify-center flex-shrink-0">
              <FileText className="w-6 h-6 text-[#2563eb]" />
            </div>
            <h1 className="text-3xl md:text-4xl font-extrabold text-[#0f2d5e]">Terms of Use</h1>
          </div>
          
          <div className="prose prose-blue max-w-none text-slate-600">
            <p className="font-medium text-lg mb-8">Last Updated: June 2026</p>

            <h2 className="text-2xl font-bold text-[#0f2d5e] mt-8 mb-4">1. Acceptance of Terms</h2>
            <p className="mb-4">
              By accessing and using the QXL Diagnostics website and our services, you accept and agree to be bound by the terms and provisions of this agreement. In addition, when using these particular services, you shall be subject to any posted guidelines or rules applicable to such services.
            </p>

            <h2 className="text-2xl font-bold text-[#0f2d5e] mt-8 mb-4">2. Diagnostic Services</h2>
            <p className="mb-4">
              QXL Diagnostics provides medical diagnostic testing and pathology services. The reports generated by our laboratory are intended to assist your physician in diagnosing and treating your medical conditions. Our reports do not constitute a medical diagnosis by themselves, and you must always consult a qualified healthcare professional for medical advice and treatment based on these reports.
            </p>

            <h2 className="text-2xl font-bold text-[#0f2d5e] mt-8 mb-4">3. Home Collection Service</h2>
            <p className="mb-4">
              When booking a home sample collection:
            </p>
            <ul className="list-disc pl-6 mb-4 space-y-2">
              <li>You agree to provide a safe environment for our phlebotomists.</li>
              <li>Appointments are subject to slot availability and geographical serviceability.</li>
              <li>While we strive to adhere strictly to requested time slots, unforeseen circumstances such as traffic or weather may cause delays.</li>
            </ul>

            <h2 className="text-2xl font-bold text-[#0f2d5e] mt-8 mb-4">4. Payment and Cancellation</h2>
            <p className="mb-4">
              Payments for tests can be made online or at the time of sample collection. If you wish to cancel an appointment, please do so at least 2 hours prior to the scheduled slot. Refunds for prepaid tests that are cancelled in accordance with our policy will be processed within 5-7 business days.
            </p>

            <h2 className="text-2xl font-bold text-[#0f2d5e] mt-8 mb-4">5. Intellectual Property</h2>
            <p className="mb-4">
              All content included on this site, such as text, graphics, logos, button icons, images, and software, is the property of QXL Diagnostics or its content suppliers and protected by international copyright laws.
            </p>

            <h2 className="text-2xl font-bold text-[#0f2d5e] mt-8 mb-4">6. Limitation of Liability</h2>
            <p className="mb-4">
              QXL Diagnostics shall not be liable for any special or consequential damages that result from the use of, or the inability to use, the services and products offered on this site, or the performance of the services and products.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
